#!/usr/bin/env python3
"""v2_stash.py — copy the good pictures instead of re-describing them.

CAMERON'S ORDER, 2026-08-04 (this file exists because of it):
  *"it should be using the old pictures and having AI look at the old pictures ...
  if it would just copy the pictures that it already has they would be a lot easier
  ... I need the AI that's commanding it to use the stash that stills from the
  previous videos and to use them to make the new pictures it's prompting."*

He is right, and the numbers prove it. 38 finished builds hold ~1,700 stills that
survived QC and shipped inside an approved mp4 — and 113 lock tokens recur across
builds (HOUSE in 16 builds, ROAD in 9, MARKET-TOWN in 8, SYNAGOGUE and TEMPLE in 5
each, BOAT in 4). Every one of those places was re-invented from TEXT on every new
row, which is exactly where the 27-30% reroll rate lives: row 39's colonnade
survived FOUR text cures; faces only stopped drifting when they were carried by
IMAGE (the CAST-BIBLE lesson, proven again by v2_story_cast.py). This file gives
PLACES the same cure faces got.

WHAT THIS DOES
  --scan     Index every still that shipped: a build counts as a stash source only
             if an assembled .mp4 sits in its folder (mechanical proof the stills
             survived QC). Each entry records the beat's own lock tokens, whether
             Jesus is in frame, wide/tight, night, and the beat's own scene text —
             the exact words that MADE the good picture are its description.
  --find     Search the stash by token or words ("--find SYNAGOGUE", "--find boat").
  --wire     For a new build: match its place tokens against the stash, pick the
             best approved plate per place (never a frame containing Jesus — early
             rows carry the retired V4 face), downscale it into <build>/PLACE-REF/,
             record the decision in <build>/PLACE-WIRING.json (committed), and
             write a PLACE_REFS dict into beats_v2.py. v2_gen_api attaches each
             plate as a PLACE LOCK image to every beat whose `locks` name it.
  --promote  After a NEW place's first good frame passes QC, promote that frame to
             be the plate for the build's remaining beats (and, once the build
             ships, the stash carries it for every later story).

WHY THE PLATE CARRIES PLACE, NOT LIGHT. The attachment preamble tells the model to
take ONLY location, architecture, materials and scale from the plate — time of day,
weather and people come from the prompt text. Relighting a known place is easy for
the model; inventing consistent architecture from prose 19 times is what failed.

CROSS-MACHINE. Plates are art (*.jpeg is gitignored); PLACE-WIRING.json is the
committed record. A machine without the source stills re-runs `--wire` to rebuild
the plates locally, or generates with `v2_gen_api.py --no-plates` (loud, explicit).

MONEY. This spends nothing — it only copies files. It exists to CUT spend: every
reroll a plate prevents is $0.134 kept.

Usage:
    python3 media-production-v2/v2_stash.py --scan
    python3 media-production-v2/v2_stash.py --find SYNAGOGUE
    python3 media-production-v2/v2_stash.py --wire build-40-the-friend-at-midnight
    python3 media-production-v2/v2_stash.py --wire build-41-counting-the-cost \
        --take HALL=build-35-great-banquet:s05
    python3 media-production-v2/v2_stash.py --promote build-40-the-friend-at-midnight \
        NEIGHBOR-HOUSE n03-door.jpeg
"""
import argparse
import glob
import json
import os
import re
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

from v2_prompt import _below_2k, load_beats  # noqa: E402
from v2_story_cast import BODY, GLOBAL_CAST  # noqa: E402

INDEX = os.path.join(HERE, "STASH-INDEX.json")
PLATE_DIR = "PLACE-REF"
WIRING = "PLACE-WIRING.json"
BLOCK_START = "# === PLACE-PLATES (generated by v2_stash.py; edit via the tool, not by hand) ==="
BLOCK_END = "# === end PLACE-PLATES ==="
NIGHT_TOKENS = {"NIGHT-LAMPLIGHT", "SEA-NIGHT"}
# Some builds carry night inside their own lock/scene prose instead of the shared
# token (build-40's whole story is midnight, zero NIGHT-LAMPLIGHT beats) — so
# night is detected from words too, on both the plate side and the target side.
NIGHT_WORDS = re.compile(
    r"\b(night|midnight|moonless|moonlit|starlit|starlight|after dark|"
    r"before dawn|pitch dark)\b", re.I)


def _is_night(beat, mod):
    toks = beat.get("locks", [])
    if any(t in NIGHT_TOKENS for t in toks):
        return True
    text = str(beat.get("scene", "")) + " ".join(
        mod.LOCKS.get(t, "") or "" for t in toks if t in getattr(mod, "LOCKS", {}))
    return bool(NIGHT_WORDS.search(text))

# Curated families of WORLD-LEVEL places — architecture and landscape that must
# look like one world across all 200 videos. Only these auto-wire; anything else
# (interiors, story-specific rooms) is SUGGESTED and wired with --take, because a
# rich man's hall and a widow's room share a token but not a look. Conservative on
# purpose: a wrong plate costs rerolls, a missing one only costs what we pay today.
AUTO_FAMILIES = {
    "TEMPLE": ["TEMPLE", "TEMPLE-COURT"],
    "SYNAGOGUE": ["SYNAGOGUE"],
    "JERUSALEM": ["JERUSALEM"],
    "CAPERNAUM": ["CAPERNAUM"],
    "TOWN": ["MARKET-TOWN", "MARKET", "TOWN", "VILLAGE", "VILLAGE-LANE", "LANE"],
    "ROAD": ["ROAD", "ROADS", "ROADSIDE", "ANCIENT-ROAD"],
    "COUNTRY": ["JUDEAN-LAND", "HILL", "PLAIN"],
    "MOUNT": ["MOUNT", "MOUNTAIN", "SUMMIT", "OLIVET"],
    "SHORE": ["SHORE"],
    "SEA-NIGHT": ["SEA-NIGHT"],
    "DESERT": ["DESERT", "WILD", "WILDS"],
    "FIELD": ["FIELD"],
    "VINEYARD": ["VINEYARD"],
    "GARDEN": ["GARDEN"],
    # An olive grove is NOT a walled kitchen garden — caught on build-40, whose
    # dawn olive-grove GROVE was wired to the mustard seed's garden beds.
    "GROVE": ["GROVE"],
    "TOMB": ["TOMB", "TOMBS"],
    "STABLE": ["STABLE"],
    "BOAT": ["BOAT"],
    "GATE": ["GATEWAY", "COURTYARD-GATE"],
    "SHEEPFOLD": ["FOLD"],
}
TOKEN_TO_FAMILY = {}
for fam, members in AUTO_FAMILIES.items():
    for m in members:
        TOKEN_TO_FAMILY[m] = fam

# Tokens that are never places no matter what the regex thinks.
CAST_TOKENS = set(GLOBAL_CAST) | {"JESUS", "TWELVE-CANONICAL", "DISCIPLES", "CROWD",
                                  "LISTENERS", "CAMERA", "BACKGROUND-CAST"}


def row_of(build_dir):
    m = re.match(r"build-(\d+)", os.path.basename(build_dir.rstrip(os.sep)))
    return int(m.group(1)) if m else None


def person_tokens(mod):
    """Tokens in a build's LOCKS that describe a body (v2_story_cast's proven
    heuristic) plus the global cast — used to keep people out of place wiring
    and to prefer people-light plates."""
    out = set(t for t in getattr(mod, "LOCKS", {}) if BODY.search(mod.LOCKS[t] or ""))
    return out | CAST_TOKENS


def scan():
    entries = []
    builds = sorted(glob.glob(os.path.join(HERE, "build-*")), key=lambda d: row_of(d) or 10**9)
    sources = skipped = 0
    for bdir in builds:
        if not os.path.isfile(os.path.join(bdir, "beats_v2.py")):
            continue
        if not glob.glob(os.path.join(bdir, "*.mp4")):
            skipped += 1
            continue  # no assembled mp4 = the stills never survived QC = not stash
        try:
            mod = load_beats(bdir)
        except SystemExit:
            continue
        except Exception as e:
            print(f"  SKIP {os.path.basename(bdir)}: beats load failed: {e}")
            continue
        assets = os.path.join(bdir, getattr(mod, "OUTPUT_ASSET_DIR", "assets"))
        people = person_tokens(mod)
        n = 0
        for beat in mod.BEATS:
            path = os.path.join(assets, beat["out"])
            if not os.path.isfile(path) or os.path.getsize(path) < 200000 or _below_2k(path):
                continue
            toks = list(beat.get("locks", []))
            entries.append({
                "row": row_of(bdir),
                "build": os.path.basename(bdir),
                "beat": beat["id"],
                "file": os.path.relpath(path, HERE),
                "tokens": toks,
                "jesus": bool(beat.get("jesus")),
                "wide": bool(beat.get("wide")),
                "night": _is_night(beat, mod),
                "n_person": sum(1 for t in toks if t in people) + (1 if beat.get("jesus") else 0),
                "scene": " ".join(str(beat.get("scene", "")).split())[:220],
            })
            n += 1
        if n:
            sources += 1
    with open(INDEX, "w") as f:
        json.dump({"scanned": time.strftime("%Y-%m-%d %H:%M:%S"), "entries": entries}, f, indent=1)
    print(f"stash: {len(entries)} shipped stills from {sources} finished builds "
          f"({skipped} builds skipped: no assembled mp4) -> {os.path.basename(INDEX)}")


def load_index(auto=True):
    if not os.path.isfile(INDEX):
        if not auto:
            raise SystemExit("no STASH-INDEX.json — run --scan first")
        print("(no index yet — scanning first)")
        scan()
    with open(INDEX) as f:
        return json.load(f)["entries"]


def find(terms):
    entries = load_index()
    terms_up = [t.upper() for t in terms]
    terms_low = [t.lower() for t in terms]
    hits = [e for e in entries
            if all(tu in e["tokens"] or tl in e["scene"].lower()
                   for tu, tl in zip(terms_up, terms_low))]
    hits.sort(key=lambda e: (-e["row"], e["beat"]))
    for e in hits:
        marks = ("[wide]" if e["wide"] else "") + ("[jesus]" if e["jesus"] else "") \
            + ("[night]" if e["night"] else "")
        print(f"{e['build']} {e['beat']} {marks}  tokens={','.join(e['tokens'])}")
        print(f"    {e['file']}")
        print(f"    {e['scene'][:150]}")
    print(f"{len(hits)} match(es)")


def _score(e, want_night):
    s = 0.0
    if e["wide"]:
        s += 3          # an establishing frame is the best plate
    if e["row"] >= 16:
        s += 2          # mature-lock era
    s += max(0, 2 - e["n_person"])   # the cleaner the frame, the safer the plate
    if want_night is not None and e["night"] == want_night:
        s += 1.5
    return s + e["row"] / 100.0      # tiebreak toward the newest lessons


def _plate_copy(src_abs, dst_abs):
    """Downscale a 2K still to a ~1024-wide plate so five attachments never
    threaten the API's request-size limit. Place identity survives downscale."""
    os.makedirs(os.path.dirname(dst_abs), exist_ok=True)
    r = subprocess.run(["ffmpeg", "-y", "-loglevel", "error", "-i", src_abs,
                        "-vf", "scale=1024:-2", "-q:v", "3", dst_abs])
    if r.returncode != 0 or not os.path.isfile(dst_abs) or os.path.getsize(dst_abs) < 20000:
        raise SystemExit(f"plate downscale failed: {src_abs} -> {dst_abs}")


def _load_wiring(bdir):
    p = os.path.join(bdir, WIRING)
    if os.path.isfile(p):
        with open(p) as f:
            return json.load(f)
    return {}


def _write_wiring_and_block(bdir, wiring):
    with open(os.path.join(bdir, WIRING), "w") as f:
        json.dump(wiring, f, indent=1, sort_keys=True)
    lines = [BLOCK_START,
             "# Each token's plate is attached as a PLACE LOCK image to every beat whose",
             "# `locks` name it. Plates live in PLACE-REF/ (gitignored art); PLACE-WIRING.json",
             "# is the committed record — `v2_stash.py --wire <this build>` rebuilds the",
             "# plates on any machine that has the source builds' stills.",
             "PLACE_REFS = {"]
    for tok in sorted(wiring):
        w = wiring[tok]
        lines.append(f'    "{tok}": "{PLATE_DIR}/{tok.lower()}.jpeg",'
                     f'  # {w["src_build"]} {w["src_beat"]}'
                     f'{" (manual)" if w.get("manual") else ""}')
    lines.append("}")
    lines.append(BLOCK_END)
    block = "\n".join(lines)

    beats_path = os.path.join(bdir, "beats_v2.py")
    src = open(beats_path).read()
    if BLOCK_START in src:
        pre, rest = src.split(BLOCK_START, 1)
        _, post = rest.split(BLOCK_END, 1)
        new = pre + block + post
    else:
        new = src.rstrip("\n") + "\n\n\n" + block + "\n"
    with open(beats_path, "w") as f:
        f.write(new)


def _resolve_take(entries, spec):
    """'TOKEN=build-dir:beat_id' -> (token, entry)."""
    tok, _, ref = spec.partition("=")
    b, _, beat = ref.partition(":")
    for e in entries:
        if e["build"] == b and e["beat"] == beat:
            return tok, e
    raise SystemExit(f"--take {spec}: no shipped still {b} {beat} in the stash "
                     "(is that build finished, and was --scan run since?)")


def wire(build_dir, takes):
    bdir = os.path.abspath(build_dir)
    if not os.path.isfile(os.path.join(bdir, "beats_v2.py")):
        raise SystemExit(f"no beats_v2.py in {bdir}")
    entries = load_index()
    self_build = os.path.basename(bdir)
    entries = [e for e in entries if e["build"] != self_build]
    mod = load_beats(bdir)
    people = person_tokens(mod)

    used_by = {}       # token -> [beat ids]
    night_votes = {}   # token -> [bool per beat]
    for beat in mod.BEATS:
        toks = beat.get("locks", [])
        is_night = _is_night(beat, mod)
        for t in toks:
            used_by.setdefault(t, []).append(beat["id"])
            night_votes.setdefault(t, []).append(is_night)

    wiring = _load_wiring(bdir)
    # Manual entries survive re-runs; auto entries are recomputed every run.
    wiring = {t: w for t, w in wiring.items() if w.get("manual")}

    for spec in takes or []:
        tok, e = _resolve_take(entries, spec)
        wiring[tok] = {"src_build": e["build"], "src_beat": e["beat"],
                       "src_file": e["file"], "manual": True}

    suggestions, new_places = [], []
    for tok in sorted(used_by):
        if tok in wiring or tok in NIGHT_TOKENS or tok in people:
            continue
        fam = TOKEN_TO_FAMILY.get(tok)
        want_night = (sum(night_votes[tok]) * 2 > len(night_votes[tok]))
        if fam:
            members = set(AUTO_FAMILIES[fam])
            cands = [e for e in entries
                     if not e["jesus"] and members.intersection(e["tokens"])]
            if cands:
                best = max(cands, key=lambda e: _score(e, want_night))
                wiring[tok] = {"src_build": best["build"], "src_beat": best["beat"],
                               "src_file": best["file"], "manual": False}
            else:
                new_places.append(tok)
        else:
            cands = [e for e in entries if not e["jesus"] and tok in e["tokens"]]
            if cands:
                best = max(cands, key=lambda e: _score(e, want_night))
                suggestions.append((tok, best))
            elif tok in getattr(mod, "LOCKS", {}):
                new_places.append(tok)

    for tok, w in sorted(wiring.items()):
        src_abs = os.path.join(HERE, w["src_file"])
        if not os.path.isfile(src_abs):
            raise SystemExit(f"{tok}: stash still missing on this machine: {w['src_file']} "
                             "— re-run --scan, or wire on the machine that generated it")
        _plate_copy(src_abs, os.path.join(bdir, PLATE_DIR, f"{tok.lower()}.jpeg"))

    _write_wiring_and_block(bdir, wiring)

    print(f"=== {self_build}: {len(wiring)} place plate(s) wired ===")
    for tok, w in sorted(wiring.items()):
        print(f"  {tok:<18} <- {w['src_build']} {w['src_beat']}"
              f"{' (manual)' if w.get('manual') else ''}"
              f"   ({len(used_by[tok])} beat(s) here)")
    if suggestions:
        print("SUGGESTED (story-specific token seen in earlier builds — confirm with --take):")
        for tok, e in suggestions:
            print(f"  --take {tok}={e['build']}:{e['beat']}   # {e['scene'][:90]}")
    if new_places:
        print("NEW PLACES (no stash match — after each one's first good frame passes QC,")
        print("promote it so the REST of the build copies that frame):")
        for tok in new_places:
            print(f"  python3 media-production-v2/v2_stash.py --promote {self_build} {tok} <that-frame.jpeg>")
    if not wiring and not suggestions and not new_places:
        print("  (no place tokens found — nothing to wire)")


def promote(build_dir, token, asset):
    bdir = os.path.abspath(build_dir)
    mod = load_beats(bdir)
    src = asset if os.path.isabs(asset) else os.path.join(
        bdir, getattr(mod, "OUTPUT_ASSET_DIR", "assets"), asset)
    if not os.path.isfile(src):
        raise SystemExit(f"no such still: {src}")
    tok = token.upper()
    used = [b["id"] for b in mod.BEATS if tok in b.get("locks", [])]
    if not used:
        raise SystemExit(f"{tok}: no beat in this build names that lock token")
    wiring = _load_wiring(bdir)
    wiring[tok] = {"src_build": os.path.basename(bdir),
                   "src_beat": os.path.splitext(os.path.basename(asset))[0],
                   "src_file": os.path.relpath(src, HERE), "manual": True}
    _plate_copy(src, os.path.join(bdir, PLATE_DIR, f"{tok.lower()}.jpeg"))
    _write_wiring_and_block(bdir, wiring)
    print(f"{tok}: promoted {os.path.basename(src)} as the plate for "
          f"{len(used)} beat(s): {', '.join(used)}")
    print("Regenerate the remaining beats of this place normally — the plate now attaches.")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--scan", action="store_true", help="rebuild STASH-INDEX.json")
    ap.add_argument("--find", nargs="+", metavar="TERM",
                    help="search the stash by lock token or scene words")
    ap.add_argument("--wire", metavar="BUILD",
                    help="wire approved place plates into this build")
    ap.add_argument("--take", nargs="*", default=None, metavar="TOKEN=build:beat",
                    help="with --wire: manually pick a plate for a token")
    ap.add_argument("--promote", nargs=3, metavar=("BUILD", "TOKEN", "ASSET"),
                    help="make one of this build's own good frames the plate for a token")
    a = ap.parse_args()
    if a.scan:
        scan()
    if a.find:
        find(a.find)
    if a.wire:
        d = a.wire if os.path.isabs(a.wire) else os.path.join(HERE, a.wire)
        wire(d, a.take)
    if a.promote:
        b, tok, asset = a.promote
        d = b if os.path.isabs(b) else os.path.join(HERE, b)
        promote(d, tok, asset)
    if not (a.scan or a.find or a.wire or a.promote):
        ap.print_help()


if __name__ == "__main__":
    main()
