// AUTO-GENERATED by tools/gen_kjv.js — do not edit by hand.
//
// Inline, public-domain King James Version text for the 100 MILK (Bible-only)
// content items, keyed by content id. Rendered in-app by ContentCard so a seeker
// never has to leave for a foundational verse.
//
// COPYRIGHT NOTE: Modern editions of the Book of Mormon, Doctrine and Covenants,
// and Pearl of Great Price (including their headings and footnotes) are
// copyrighted by The Church of Jesus Christ of Latter-day Saints. Only
// public-domain KJV text is embedded here, and only for the milk track. MEAT
// (restored-scripture) items NEVER embed text — they link to the official
// Gospel Library instead. See ContentCard.tsx.

export interface KjvVerse { ref: string; text: string }

export const KJV_TEXT: Record<number, KjvVerse[]> = {
  "1": [
    {
      "ref": "John 14:27",
      "text": "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid."
    }
  ],
  "2": [
    {
      "ref": "Matthew 11:28",
      "text": "Come unto me, all ye that labour and are heavy laden, and I will give you rest."
    },
    {
      "ref": "Matthew 11:29",
      "text": "Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls."
    },
    {
      "ref": "Matthew 11:30",
      "text": "For my yoke is easy, and my burden is light."
    }
  ],
  "3": [
    {
      "ref": "Psalms 23:1",
      "text": "The LORD is my shepherd; I shall not want."
    },
    {
      "ref": "Psalms 23:2",
      "text": "He maketh me to lie down in green pastures: he leadeth me beside the still waters."
    },
    {
      "ref": "Psalms 23:3",
      "text": "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake."
    },
    {
      "ref": "Psalms 23:4",
      "text": "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me; thy rod and thy staff they comfort me."
    },
    {
      "ref": "Psalms 23:5",
      "text": "Thou preparest a table before me in the presence of mine enemies: thou anointest my head with oil; my cup runneth over."
    },
    {
      "ref": "Psalms 23:6",
      "text": "Surely goodness and mercy shall follow me all the days of my life: and I will dwell in the house of the LORD for ever."
    }
  ],
  "4": [
    {
      "ref": "John 3:16",
      "text": "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life."
    }
  ],
  "5": [
    {
      "ref": "Luke 15:11",
      "text": "And he said, A certain man had two sons:"
    },
    {
      "ref": "Luke 15:12",
      "text": "And the younger of them said to his father, Father, give me the portion of goods that falleth to me. And he divided unto them his living."
    },
    {
      "ref": "Luke 15:13",
      "text": "And not many days after the younger son gathered all together, and took his journey into a far country, and there wasted his substance with riotous living."
    },
    {
      "ref": "Luke 15:14",
      "text": "And when he had spent all, there arose a mighty famine in that land; and he began to be in want."
    },
    {
      "ref": "Luke 15:15",
      "text": "And he went and joined himself to a citizen of that country; and he sent him into his fields to feed swine."
    },
    {
      "ref": "Luke 15:16",
      "text": "And he would fain have filled his belly with the husks that the swine did eat: and no man gave unto him."
    },
    {
      "ref": "Luke 15:17",
      "text": "And when he came to himself, he said, How many hired servants of my father's have bread enough and to spare, and I perish with hunger!"
    },
    {
      "ref": "Luke 15:18",
      "text": "I will arise and go to my father, and will say unto him, Father, I have sinned against heaven, and before thee,"
    },
    {
      "ref": "Luke 15:19",
      "text": "And am no more worthy to be called thy son: make me as one of thy hired servants."
    },
    {
      "ref": "Luke 15:20",
      "text": "And he arose, and came to his father. But when he was yet a great way off, his father saw him, and had compassion, and ran, and fell on his neck, and kissed him."
    },
    {
      "ref": "Luke 15:21",
      "text": "And the son said unto him, Father, I have sinned against heaven, and in thy sight, and am no more worthy to be called thy son."
    },
    {
      "ref": "Luke 15:22",
      "text": "But the father said to his servants, Bring forth the best robe, and put it on him; and put a ring on his hand, and shoes on his feet:"
    },
    {
      "ref": "Luke 15:23",
      "text": "And bring hither the fatted calf, and kill it; and let us eat, and be merry:"
    },
    {
      "ref": "Luke 15:24",
      "text": "For this my son was dead, and is alive again; he was lost, and is found. And they began to be merry."
    },
    {
      "ref": "Luke 15:25",
      "text": "Now his elder son was in the field: and as he came and drew nigh to the house, he heard musick and dancing."
    },
    {
      "ref": "Luke 15:26",
      "text": "And he called one of the servants, and asked what these things meant."
    },
    {
      "ref": "Luke 15:27",
      "text": "And he said unto him, Thy brother is come; and thy father hath killed the fatted calf, because he hath received him safe and sound."
    },
    {
      "ref": "Luke 15:28",
      "text": "And he was angry, and would not go in: therefore came his father out, and intreated him."
    },
    {
      "ref": "Luke 15:29",
      "text": "And he answering said to his father, Lo, these many years do I serve thee, neither transgressed I at any time thy commandment: and yet thou never gavest me a kid, that I might make merry with my friends:"
    },
    {
      "ref": "Luke 15:30",
      "text": "But as soon as this thy son was come, which hath devoured thy living with harlots, thou hast killed for him the fatted calf."
    },
    {
      "ref": "Luke 15:31",
      "text": "And he said unto him, Son, thou art ever with me, and all that I have is thine."
    },
    {
      "ref": "Luke 15:32",
      "text": "It was meet that we should make merry, and be glad: for this thy brother was dead, and is alive again; and was lost, and is found."
    }
  ],
  "6": [
    {
      "ref": "Luke 15:3",
      "text": "And he spake this parable unto them, saying,"
    },
    {
      "ref": "Luke 15:4",
      "text": "What man of you, having an hundred sheep, if he lose one of them, doth not leave the ninety and nine in the wilderness, and go after that which is lost, until he find it?"
    },
    {
      "ref": "Luke 15:5",
      "text": "And when he hath found it, he layeth it on his shoulders, rejoicing."
    },
    {
      "ref": "Luke 15:6",
      "text": "And when he cometh home, he calleth together his friends and neighbours, saying unto them, Rejoice with me; for I have found my sheep which was lost."
    },
    {
      "ref": "Luke 15:7",
      "text": "I say unto you, that likewise joy shall be in heaven over one sinner that repenteth, more than over ninety and nine just persons, which need no repentance."
    }
  ],
  "7": [
    {
      "ref": "John 8:1",
      "text": "Jesus went unto the mount of Olives."
    },
    {
      "ref": "John 8:2",
      "text": "And early in the morning he came again into the temple, and all the people came unto him; and he sat down, and taught them."
    },
    {
      "ref": "John 8:3",
      "text": "And the scribes and Pharisees brought unto him a woman taken in adultery; and when they had set her in the midst,"
    },
    {
      "ref": "John 8:4",
      "text": "They say unto him, Master, this woman was taken in adultery, in the very act."
    },
    {
      "ref": "John 8:5",
      "text": "Now Moses in the law commanded us, that such should be stoned: but what sayest thou?"
    },
    {
      "ref": "John 8:6",
      "text": "This they said, tempting him, that they might have to accuse him. But Jesus stooped down, and with his finger wrote on the ground, as though he heard them not."
    },
    {
      "ref": "John 8:7",
      "text": "So when they continued asking him, he lifted up himself, and said unto them, He that is without sin among you, let him first cast a stone at her."
    },
    {
      "ref": "John 8:8",
      "text": "And again he stooped down, and wrote on the ground."
    },
    {
      "ref": "John 8:9",
      "text": "And they which heard it, being convicted by their own conscience, went out one by one, beginning at the eldest, even unto the last: and Jesus was left alone, and the woman standing in the midst."
    },
    {
      "ref": "John 8:10",
      "text": "When Jesus had lifted up himself, and saw none but the woman, he said unto her, Woman, where are those thine accusers? hath no man condemned thee?"
    },
    {
      "ref": "John 8:11",
      "text": "She said, No man, Lord. And Jesus said unto her, Neither do I condemn thee: go, and sin no more."
    }
  ],
  "8": [
    {
      "ref": "Matthew 5:3",
      "text": "Blessed are the poor in spirit: for their's is the kingdom of heaven."
    },
    {
      "ref": "Matthew 5:4",
      "text": "Blessed are they that mourn: for they shall be comforted."
    },
    {
      "ref": "Matthew 5:5",
      "text": "Blessed are the meek: for they shall inherit the earth."
    },
    {
      "ref": "Matthew 5:6",
      "text": "Blessed are they which do hunger and thirst after righteousness: for they shall be filled."
    },
    {
      "ref": "Matthew 5:7",
      "text": "Blessed are the merciful: for they shall obtain mercy."
    },
    {
      "ref": "Matthew 5:8",
      "text": "Blessed are the pure in heart: for they shall see God."
    },
    {
      "ref": "Matthew 5:9",
      "text": "Blessed are the peacemakers: for they shall be called the children of God."
    },
    {
      "ref": "Matthew 5:10",
      "text": "Blessed are they which are persecuted for righteousness' sake: for their's is the kingdom of heaven."
    },
    {
      "ref": "Matthew 5:11",
      "text": "Blessed are ye, when men shall revile you, and persecute you, and shall say all manner of evil against you falsely, for my sake."
    },
    {
      "ref": "Matthew 5:12",
      "text": "Rejoice, and be exceeding glad: for great is your reward in heaven: for so persecuted they the prophets which were before you."
    }
  ],
  "9": [
    {
      "ref": "John 11:35",
      "text": "Jesus wept."
    }
  ],
  "10": [
    {
      "ref": "Luke 10:25",
      "text": "And, behold, a certain lawyer stood up, and tempted him, saying, Master, what shall I do to inherit eternal life?"
    },
    {
      "ref": "Luke 10:26",
      "text": "He said unto him, What is written in the law? how readest thou?"
    },
    {
      "ref": "Luke 10:27",
      "text": "And he answering said, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy strength, and with all thy mind; and thy neighbour as thyself."
    },
    {
      "ref": "Luke 10:28",
      "text": "And he said unto him, Thou hast answered right: this do, and thou shalt live."
    },
    {
      "ref": "Luke 10:29",
      "text": "But he, willing to justify himself, said unto Jesus, And who is my neighbour?"
    },
    {
      "ref": "Luke 10:30",
      "text": "And Jesus answering said, A certain man went down from Jerusalem to Jericho, and fell among thieves, which stripped him of his raiment, and wounded him, and departed, leaving him half dead."
    },
    {
      "ref": "Luke 10:31",
      "text": "And by chance there came down a certain priest that way: and when he saw him, he passed by on the other side."
    },
    {
      "ref": "Luke 10:32",
      "text": "And likewise a Levite, when he was at the place, came and looked on him, and passed by on the other side."
    },
    {
      "ref": "Luke 10:33",
      "text": "But a certain Samaritan, as he journeyed, came where he was: and when he saw him, he had compassion on him,"
    },
    {
      "ref": "Luke 10:34",
      "text": "And went to him, and bound up his wounds, pouring in oil and wine, and set him on his own beast, and brought him to an inn, and took care of him."
    },
    {
      "ref": "Luke 10:35",
      "text": "And on the morrow when he departed, he took out two pence, and gave them to the host, and said unto him, Take care of him; and whatsoever thou spendest more, when I come again, I will repay thee."
    },
    {
      "ref": "Luke 10:36",
      "text": "Which now of these three, thinkest thou, was neighbour unto him that fell among the thieves?"
    },
    {
      "ref": "Luke 10:37",
      "text": "And he said, He that shewed mercy on him. Then said Jesus unto him, Go, and do thou likewise."
    }
  ],
  "11": [
    {
      "ref": "Matthew 6:9",
      "text": "After this manner therefore pray ye: Our Father which art in heaven, Hallowed be thy name."
    },
    {
      "ref": "Matthew 6:10",
      "text": "Thy kingdom come. Thy will be done in earth, as it is in heaven."
    },
    {
      "ref": "Matthew 6:11",
      "text": "Give us this day our daily bread."
    },
    {
      "ref": "Matthew 6:12",
      "text": "And forgive us our debts, as we forgive our debtors."
    },
    {
      "ref": "Matthew 6:13",
      "text": "And lead us not into temptation, but deliver us from evil: For thine is the kingdom, and the power, and the glory, for ever. Amen."
    }
  ],
  "12": [
    {
      "ref": "Isaiah 41:10",
      "text": "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness."
    }
  ],
  "13": [
    {
      "ref": "Psalms 46:1",
      "text": "God is our refuge and strength, a very present help in trouble."
    }
  ],
  "14": [
    {
      "ref": "Romans 8:38",
      "text": "For I am persuaded, that neither death, nor life, nor angels, nor principalities, nor powers, nor things present, nor things to come,"
    },
    {
      "ref": "Romans 8:39",
      "text": "Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God, which is in Christ Jesus our Lord."
    }
  ],
  "15": [
    {
      "ref": "Matthew 7:7",
      "text": "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you:"
    }
  ],
  "16": [
    {
      "ref": "John 10:11",
      "text": "I am the good shepherd: the good shepherd giveth his life for the sheep."
    }
  ],
  "17": [
    {
      "ref": "Mark 5:25",
      "text": "And a certain woman, which had an issue of blood twelve years,"
    },
    {
      "ref": "Mark 5:26",
      "text": "And had suffered many things of many physicians, and had spent all that she had, and was nothing bettered, but rather grew worse,"
    },
    {
      "ref": "Mark 5:27",
      "text": "When she had heard of Jesus, came in the press behind, and touched his garment."
    },
    {
      "ref": "Mark 5:28",
      "text": "For she said, If I may touch but his clothes, I shall be whole."
    },
    {
      "ref": "Mark 5:29",
      "text": "And straightway the fountain of her blood was dried up; and she felt in her body that she was healed of that plague."
    },
    {
      "ref": "Mark 5:30",
      "text": "And Jesus, immediately knowing in himself that virtue had gone out of him, turned him about in the press, and said, Who touched my clothes?"
    },
    {
      "ref": "Mark 5:31",
      "text": "And his disciples said unto him, Thou seest the multitude thronging thee, and sayest thou, Who touched me?"
    },
    {
      "ref": "Mark 5:32",
      "text": "And he looked round about to see her that had done this thing."
    },
    {
      "ref": "Mark 5:33",
      "text": "But the woman fearing and trembling, knowing what was done in her, came and fell down before him, and told him all the truth."
    },
    {
      "ref": "Mark 5:34",
      "text": "And he said unto her, Daughter, thy faith hath made thee whole; go in peace, and be whole of thy plague."
    }
  ],
  "18": [
    {
      "ref": "Luke 19:1",
      "text": "And Jesus entered and passed through Jericho."
    },
    {
      "ref": "Luke 19:2",
      "text": "And, behold, there was a man named Zacchaeus, which was the chief among the publicans, and he was rich."
    },
    {
      "ref": "Luke 19:3",
      "text": "And he sought to see Jesus who he was; and could not for the press, because he was little of stature."
    },
    {
      "ref": "Luke 19:4",
      "text": "And he ran before, and climbed up into a sycomore tree to see him: for he was to pass that way."
    },
    {
      "ref": "Luke 19:5",
      "text": "And when Jesus came to the place, he looked up, and saw him, and said unto him, Zacchaeus, make haste, and come down; for to day I must abide at thy house."
    },
    {
      "ref": "Luke 19:6",
      "text": "And he made haste, and came down, and received him joyfully."
    },
    {
      "ref": "Luke 19:7",
      "text": "And when they saw it, they all murmured, saying, That he was gone to be guest with a man that is a sinner."
    },
    {
      "ref": "Luke 19:8",
      "text": "And Zacchaeus stood, and said unto the Lord; Behold, Lord, the half of my goods I give to the poor; and if I have taken any thing from any man by false accusation, I restore him fourfold."
    },
    {
      "ref": "Luke 19:9",
      "text": "And Jesus said unto him, This day is salvation come to this house, forsomuch as he also is a son of Abraham."
    },
    {
      "ref": "Luke 19:10",
      "text": "For the Son of man is come to seek and to save that which was lost."
    }
  ],
  "19": [
    {
      "ref": "John 4:1",
      "text": "When therefore the Lord knew how the Pharisees had heard that Jesus made and baptized more disciples than John,"
    },
    {
      "ref": "John 4:2",
      "text": "(Though Jesus himself baptized not, but his disciples,)"
    },
    {
      "ref": "John 4:3",
      "text": "He left Judaea, and departed again into Galilee."
    },
    {
      "ref": "John 4:4",
      "text": "And he must needs go through Samaria."
    },
    {
      "ref": "John 4:5",
      "text": "Then cometh he to a city of Samaria, which is called Sychar, near to the parcel of ground that Jacob gave to his son Joseph."
    },
    {
      "ref": "John 4:6",
      "text": "Now Jacob's well was there. Jesus therefore, being wearied with his journey, sat thus on the well: and it was about the sixth hour."
    },
    {
      "ref": "John 4:7",
      "text": "There cometh a woman of Samaria to draw water: Jesus saith unto her, Give me to drink."
    },
    {
      "ref": "John 4:8",
      "text": "(For his disciples were gone away unto the city to buy meat.)"
    },
    {
      "ref": "John 4:9",
      "text": "Then saith the woman of Samaria unto him, How is it that thou, being a Jew, askest drink of me, which am a woman of Samaria? for the Jews have no dealings with the Samaritans."
    },
    {
      "ref": "John 4:10",
      "text": "Jesus answered and said unto her, If thou knewest the gift of God, and who it is that saith to thee, Give me to drink; thou wouldest have asked of him, and he would have given thee living water."
    },
    {
      "ref": "John 4:11",
      "text": "The woman saith unto him, Sir, thou hast nothing to draw with, and the well is deep: from whence then hast thou that living water?"
    },
    {
      "ref": "John 4:12",
      "text": "Art thou greater than our father Jacob, which gave us the well, and drank thereof himself, and his children, and his cattle?"
    },
    {
      "ref": "John 4:13",
      "text": "Jesus answered and said unto her, Whosoever drinketh of this water shall thirst again:"
    },
    {
      "ref": "John 4:14",
      "text": "But whosoever drinketh of the water that I shall give him shall never thirst; but the water that I shall give him shall be in him a well of water springing up into everlasting life."
    },
    {
      "ref": "John 4:15",
      "text": "The woman saith unto him, Sir, give me this water, that I thirst not, neither come hither to draw."
    },
    {
      "ref": "John 4:16",
      "text": "Jesus saith unto her, Go, call thy husband, and come hither."
    },
    {
      "ref": "John 4:17",
      "text": "The woman answered and said, I have no husband. Jesus said unto her, Thou hast well said, I have no husband:"
    },
    {
      "ref": "John 4:18",
      "text": "For thou hast had five husbands; and he whom thou now hast is not thy husband: in that saidst thou truly."
    },
    {
      "ref": "John 4:19",
      "text": "The woman saith unto him, Sir, I perceive that thou art a prophet."
    },
    {
      "ref": "John 4:20",
      "text": "Our fathers worshipped in this mountain; and ye say, that in Jerusalem is the place where men ought to worship."
    },
    {
      "ref": "John 4:21",
      "text": "Jesus saith unto her, Woman, believe me, the hour cometh, when ye shall neither in this mountain, nor yet at Jerusalem, worship the Father."
    },
    {
      "ref": "John 4:22",
      "text": "Ye worship ye know not what: we know what we worship: for salvation is of the Jews."
    },
    {
      "ref": "John 4:23",
      "text": "But the hour cometh, and now is, when the true worshippers shall worship the Father in spirit and in truth: for the Father seeketh such to worship him."
    },
    {
      "ref": "John 4:24",
      "text": "God is a Spirit: and they that worship him must worship him in spirit and in truth."
    },
    {
      "ref": "John 4:25",
      "text": "The woman saith unto him, I know that Messias cometh, which is called Christ: when he is come, he will tell us all things."
    },
    {
      "ref": "John 4:26",
      "text": "Jesus saith unto her, I that speak unto thee am he."
    }
  ],
  "20": [
    {
      "ref": "Matthew 14:22",
      "text": "And straightway Jesus constrained his disciples to get into a ship, and to go before him unto the other side, while he sent the multitudes away."
    },
    {
      "ref": "Matthew 14:23",
      "text": "And when he had sent the multitudes away, he went up into a mountain apart to pray: and when the evening was come, he was there alone."
    },
    {
      "ref": "Matthew 14:24",
      "text": "But the ship was now in the midst of the sea, tossed with waves: for the wind was contrary."
    },
    {
      "ref": "Matthew 14:25",
      "text": "And in the fourth watch of the night Jesus went unto them, walking on the sea."
    },
    {
      "ref": "Matthew 14:26",
      "text": "And when the disciples saw him walking on the sea, they were troubled, saying, It is a spirit; and they cried out for fear."
    },
    {
      "ref": "Matthew 14:27",
      "text": "But straightway Jesus spake unto them, saying, Be of good cheer; it is I; be not afraid."
    },
    {
      "ref": "Matthew 14:28",
      "text": "And Peter answered him and said, Lord, if it be thou, bid me come unto thee on the water."
    },
    {
      "ref": "Matthew 14:29",
      "text": "And he said, Come. And when Peter was come down out of the ship, he walked on the water, to go to Jesus."
    },
    {
      "ref": "Matthew 14:30",
      "text": "But when he saw the wind boisterous, he was afraid; and beginning to sink, he cried, saying, Lord, save me."
    },
    {
      "ref": "Matthew 14:31",
      "text": "And immediately Jesus stretched forth his hand, and caught him, and said unto him, O thou of little faith, wherefore didst thou doubt?"
    },
    {
      "ref": "Matthew 14:32",
      "text": "And when they were come into the ship, the wind ceased."
    },
    {
      "ref": "Matthew 14:33",
      "text": "Then they that were in the ship came and worshipped him, saying, Of a truth thou art the Son of God."
    }
  ],
  "21": [
    {
      "ref": "Philippians 4:6",
      "text": "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God."
    },
    {
      "ref": "Philippians 4:7",
      "text": "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus."
    }
  ],
  "22": [
    {
      "ref": "Psalms 34:18",
      "text": "The LORD is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit."
    }
  ],
  "23": [
    {
      "ref": "Revelation 21:4",
      "text": "And God shall wipe away all tears from their eyes; and there shall be no more death, neither sorrow, nor crying, neither shall there be any more pain: for the former things are passed away."
    }
  ],
  "24": [
    {
      "ref": "1 Corinthians 13:4",
      "text": "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up,"
    },
    {
      "ref": "1 Corinthians 13:5",
      "text": "Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil;"
    },
    {
      "ref": "1 Corinthians 13:6",
      "text": "Rejoiceth not in iniquity, but rejoiceth in the truth;"
    },
    {
      "ref": "1 Corinthians 13:7",
      "text": "Beareth all things, believeth all things, hopeth all things, endureth all things."
    }
  ],
  "25": [
    {
      "ref": "Matthew 5:14",
      "text": "Ye are the light of the world. A city that is set on an hill cannot be hid."
    },
    {
      "ref": "Matthew 5:15",
      "text": "Neither do men light a candle, and put it under a bushel, but on a candlestick; and it giveth light unto all that are in the house."
    },
    {
      "ref": "Matthew 5:16",
      "text": "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven."
    }
  ],
  "26": [
    {
      "ref": "John 13:34",
      "text": "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another."
    },
    {
      "ref": "John 13:35",
      "text": "By this shall all men know that ye are my disciples, if ye have love one to another."
    }
  ],
  "27": [
    {
      "ref": "Luke 23:34",
      "text": "Then said Jesus, Father, forgive them; for they know not what they do. And they parted his raiment, and cast lots."
    }
  ],
  "28": [
    {
      "ref": "Matthew 28:20",
      "text": "Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world. Amen."
    }
  ],
  "29": [
    {
      "ref": "Joshua 1:9",
      "text": "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest."
    }
  ],
  "30": [
    {
      "ref": "Jeremiah 29:11",
      "text": "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end."
    }
  ],
  "31": [
    {
      "ref": "Proverbs 3:5",
      "text": "Trust in the LORD with all thine heart; and lean not unto thine own understanding."
    },
    {
      "ref": "Proverbs 3:6",
      "text": "In all thy ways acknowledge him, and he shall direct thy paths."
    }
  ],
  "32": [
    {
      "ref": "Matthew 6:25",
      "text": "Therefore I say unto you, Take no thought for your life, what ye shall eat, or what ye shall drink; nor yet for your body, what ye shall put on. Is not the life more than meat, and the body than raiment?"
    },
    {
      "ref": "Matthew 6:26",
      "text": "Behold the fowls of the air: for they sow not, neither do they reap, nor gather into barns; yet your heavenly Father feedeth them. Are ye not much better than they?"
    },
    {
      "ref": "Matthew 6:27",
      "text": "Which of you by taking thought can add one cubit unto his stature?"
    },
    {
      "ref": "Matthew 6:28",
      "text": "And why take ye thought for raiment? Consider the lilies of the field, how they grow; they toil not, neither do they spin:"
    },
    {
      "ref": "Matthew 6:29",
      "text": "And yet I say unto you, That even Solomon in all his glory was not arrayed like one of these."
    },
    {
      "ref": "Matthew 6:30",
      "text": "Wherefore, if God so clothe the grass of the field, which to day is, and to morrow is cast into the oven, shall he not much more clothe you, O ye of little faith?"
    },
    {
      "ref": "Matthew 6:31",
      "text": "Therefore take no thought, saying, What shall we eat? or, What shall we drink? or, Wherewithal shall we be clothed?"
    },
    {
      "ref": "Matthew 6:32",
      "text": "(For after all these things do the Gentiles seek:) for your heavenly Father knoweth that ye have need of all these things."
    },
    {
      "ref": "Matthew 6:33",
      "text": "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you."
    },
    {
      "ref": "Matthew 6:34",
      "text": "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day is the evil thereof."
    }
  ],
  "33": [
    {
      "ref": "John 14:1",
      "text": "Let not your heart be troubled: ye believe in God, believe also in me."
    },
    {
      "ref": "John 14:2",
      "text": "In my Father's house are many mansions: if it were not so, I would have told you. I go to prepare a place for you."
    },
    {
      "ref": "John 14:3",
      "text": "And if I go and prepare a place for you, I will come again, and receive you unto myself; that where I am, there ye may be also."
    }
  ],
  "34": [
    {
      "ref": "Luke 18:9",
      "text": "And he spake this parable unto certain which trusted in themselves that they were righteous, and despised others:"
    },
    {
      "ref": "Luke 18:10",
      "text": "Two men went up into the temple to pray; the one a Pharisee, and the other a publican."
    },
    {
      "ref": "Luke 18:11",
      "text": "The Pharisee stood and prayed thus with himself, God, I thank thee, that I am not as other men are, extortioners, unjust, adulterers, or even as this publican."
    },
    {
      "ref": "Luke 18:12",
      "text": "I fast twice in the week, I give tithes of all that I possess."
    },
    {
      "ref": "Luke 18:13",
      "text": "And the publican, standing afar off, would not lift up so much as his eyes unto heaven, but smote upon his breast, saying, God be merciful to me a sinner."
    },
    {
      "ref": "Luke 18:14",
      "text": "I tell you, this man went down to his house justified rather than the other: for every one that exalteth himself shall be abased; and he that humbleth himself shall be exalted."
    }
  ],
  "35": [
    {
      "ref": "Matthew 18:21",
      "text": "Then came Peter to him, and said, Lord, how oft shall my brother sin against me, and I forgive him? till seven times?"
    },
    {
      "ref": "Matthew 18:22",
      "text": "Jesus saith unto him, I say not unto thee, Until seven times: but, Until seventy times seven."
    }
  ],
  "36": [
    {
      "ref": "Mark 10:13",
      "text": "And they brought young children to him, that he should touch them: and his disciples rebuked those that brought them."
    },
    {
      "ref": "Mark 10:14",
      "text": "But when Jesus saw it, he was much displeased, and said unto them, Suffer the little children to come unto me, and forbid them not: for of such is the kingdom of God."
    },
    {
      "ref": "Mark 10:15",
      "text": "Verily I say unto you, Whosoever shall not receive the kingdom of God as a little child, he shall not enter therein."
    },
    {
      "ref": "Mark 10:16",
      "text": "And he took them up in his arms, put his hands upon them, and blessed them."
    }
  ],
  "37": [
    {
      "ref": "Luke 7:36",
      "text": "And one of the Pharisees desired him that he would eat with him. And he went into the Pharisee's house, and sat down to meat."
    },
    {
      "ref": "Luke 7:37",
      "text": "And, behold, a woman in the city, which was a sinner, when she knew that Jesus sat at meat in the Pharisee's house, brought an alabaster box of ointment,"
    },
    {
      "ref": "Luke 7:38",
      "text": "And stood at his feet behind him weeping, and began to wash his feet with tears, and did wipe them with the hairs of her head, and kissed his feet, and anointed them with the ointment."
    },
    {
      "ref": "Luke 7:39",
      "text": "Now when the Pharisee which had bidden him saw it, he spake within himself, saying, This man, if he were a prophet, would have known who and what manner of woman this is that toucheth him: for she is a sinner."
    },
    {
      "ref": "Luke 7:40",
      "text": "And Jesus answering said unto him, Simon, I have somewhat to say unto thee. And he saith, Master, say on."
    },
    {
      "ref": "Luke 7:41",
      "text": "There was a certain creditor which had two debtors: the one owed five hundred pence, and the other fifty."
    },
    {
      "ref": "Luke 7:42",
      "text": "And when they had nothing to pay, he frankly forgave them both. Tell me therefore, which of them will love him most?"
    },
    {
      "ref": "Luke 7:43",
      "text": "Simon answered and said, I suppose that he, to whom he forgave most. And he said unto him, Thou hast rightly judged."
    },
    {
      "ref": "Luke 7:44",
      "text": "And he turned to the woman, and said unto Simon, Seest thou this woman? I entered into thine house, thou gavest me no water for my feet: but she hath washed my feet with tears, and wiped them with the hairs of her head."
    },
    {
      "ref": "Luke 7:45",
      "text": "Thou gavest me no kiss: but this woman since the time I came in hath not ceased to kiss my feet."
    },
    {
      "ref": "Luke 7:46",
      "text": "My head with oil thou didst not anoint: but this woman hath anointed my feet with ointment."
    },
    {
      "ref": "Luke 7:47",
      "text": "Wherefore I say unto thee, Her sins, which are many, are forgiven; for she loved much: but to whom little is forgiven, the same loveth little."
    },
    {
      "ref": "Luke 7:48",
      "text": "And he said unto her, Thy sins are forgiven."
    },
    {
      "ref": "Luke 7:49",
      "text": "And they that sat at meat with him began to say within themselves, Who is this that forgiveth sins also?"
    },
    {
      "ref": "Luke 7:50",
      "text": "And he said to the woman, Thy faith hath saved thee; go in peace."
    }
  ],
  "38": [
    {
      "ref": "John 15:13",
      "text": "Greater love hath no man than this, that a man lay down his life for his friends."
    }
  ],
  "39": [
    {
      "ref": "Psalms 139:7",
      "text": "Whither shall I go from thy spirit? or whither shall I flee from thy presence?"
    },
    {
      "ref": "Psalms 139:8",
      "text": "If I ascend up into heaven, thou art there: if I make my bed in hell, behold, thou art there."
    },
    {
      "ref": "Psalms 139:9",
      "text": "If I take the wings of the morning, and dwell in the uttermost parts of the sea;"
    },
    {
      "ref": "Psalms 139:10",
      "text": "Even there shall thy hand lead me, and thy right hand shall hold me."
    }
  ],
  "40": [
    {
      "ref": "Isaiah 53:3",
      "text": "He is despised and rejected of men; a man of sorrows, and acquainted with grief: and we hid as it were our faces from him; he was despised, and we esteemed him not."
    },
    {
      "ref": "Isaiah 53:4",
      "text": "Surely he hath borne our griefs, and carried our sorrows: yet we did esteem him stricken, smitten of God, and afflicted."
    },
    {
      "ref": "Isaiah 53:5",
      "text": "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed."
    }
  ],
  "41": [
    {
      "ref": "Matthew 9:36",
      "text": "But when he saw the multitudes, he was moved with compassion on them, because they fainted, and were scattered abroad, as sheep having no shepherd."
    }
  ],
  "42": [
    {
      "ref": "Luke 6:37",
      "text": "Judge not, and ye shall not be judged: condemn not, and ye shall not be condemned: forgive, and ye shall be forgiven:"
    }
  ],
  "43": [
    {
      "ref": "John 16:33",
      "text": "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world."
    }
  ],
  "44": [
    {
      "ref": "2 Corinthians 12:9",
      "text": "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me."
    }
  ],
  "45": [
    {
      "ref": "Hebrews 13:5",
      "text": "Let your conversation be without covetousness; and be content with such things as ye have: for he hath said, I will never leave thee, nor forsake thee."
    }
  ],
  "46": [
    {
      "ref": "Psalms 30:5",
      "text": "For his anger endureth but a moment; in his favour is life: weeping may endure for a night, but joy cometh in the morning."
    }
  ],
  "47": [
    {
      "ref": "Matthew 5:43",
      "text": "Ye have heard that it hath been said, Thou shalt love thy neighbour, and hate thine enemy."
    },
    {
      "ref": "Matthew 5:44",
      "text": "But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which despitefully use you, and persecute you;"
    },
    {
      "ref": "Matthew 5:45",
      "text": "That ye may be the children of your Father which is in heaven: for he maketh his sun to rise on the evil and on the good, and sendeth rain on the just and on the unjust."
    },
    {
      "ref": "Matthew 5:46",
      "text": "For if ye love them which love you, what reward have ye? do not even the publicans the same?"
    },
    {
      "ref": "Matthew 5:47",
      "text": "And if ye salute your brethren only, what do ye more than others? do not even the publicans so?"
    },
    {
      "ref": "Matthew 5:48",
      "text": "Be ye therefore perfect, even as your Father which is in heaven is perfect."
    }
  ],
  "48": [
    {
      "ref": "Luke 12:6",
      "text": "Are not five sparrows sold for two farthings, and not one of them is forgotten before God?"
    },
    {
      "ref": "Luke 12:7",
      "text": "But even the very hairs of your head are all numbered. Fear not therefore: ye are of more value than many sparrows."
    }
  ],
  "49": [
    {
      "ref": "John 6:35",
      "text": "And Jesus said unto them, I am the bread of life: he that cometh to me shall never hunger; and he that believeth on me shall never thirst."
    }
  ],
  "50": [
    {
      "ref": "Lamentations 3:22",
      "text": "It is of the LORD'S mercies that we are not consumed, because his compassions fail not."
    },
    {
      "ref": "Lamentations 3:23",
      "text": "They are new every morning: great is thy faithfulness."
    }
  ],
  "51": [
    {
      "ref": "John 10:34",
      "text": "Jesus answered them, Is it not written in your law, I said, Ye are gods?"
    }
  ],
  "52": [
    {
      "ref": "1 Corinthians 15:29",
      "text": "Else what shall they do which are baptized for the dead, if the dead rise not at all? why are they then baptized for the dead?"
    }
  ],
  "53": [
    {
      "ref": "Revelation 3:21",
      "text": "To him that overcometh will I grant to sit with me in my throne, even as I also overcame, and am set down with my Father in his throne."
    }
  ],
  "54": [
    {
      "ref": "Matthew 3:16",
      "text": "And Jesus, when he was baptized, went up straightway out of the water: and, lo, the heavens were opened unto him, and he saw the Spirit of God descending like a dove, and lighting upon him:"
    },
    {
      "ref": "Matthew 3:17",
      "text": "And lo a voice from heaven, saying, This is my beloved Son, in whom I am well pleased."
    }
  ],
  "55": [
    {
      "ref": "John 17:20",
      "text": "Neither pray I for these alone, but for them also which shall believe on me through their word;"
    },
    {
      "ref": "John 17:21",
      "text": "That they all may be one; as thou, Father, art in me, and I in thee, that they also may be one in us: that the world may believe that thou hast sent me."
    },
    {
      "ref": "John 17:22",
      "text": "And the glory which thou gavest me I have given them; that they may be one, even as we are one:"
    },
    {
      "ref": "John 17:23",
      "text": "I in them, and thou in me, that they may be made perfect in one; and that the world may know that thou hast sent me, and hast loved them, as thou hast loved me."
    }
  ],
  "56": [
    {
      "ref": "Acts 17:28",
      "text": "For in him we live, and move, and have our being; as certain also of your own poets have said, For we are also his offspring."
    },
    {
      "ref": "Acts 17:29",
      "text": "Forasmuch then as we are the offspring of God, we ought not to think that the Godhead is like unto gold, or silver, or stone, graven by art and man's device."
    }
  ],
  "57": [
    {
      "ref": "Romans 8:16",
      "text": "The Spirit itself beareth witness with our spirit, that we are the children of God:"
    },
    {
      "ref": "Romans 8:17",
      "text": "And if children, then heirs; heirs of God, and joint-heirs with Christ; if so be that we suffer with him, that we may be also glorified together."
    }
  ],
  "58": [
    {
      "ref": "Hebrews 12:9",
      "text": "Furthermore we have had fathers of our flesh which corrected us, and we gave them reverence: shall we not much rather be in subjection unto the Father of spirits, and live?"
    }
  ],
  "59": [
    {
      "ref": "James 1:5",
      "text": "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him."
    }
  ],
  "60": [
    {
      "ref": "Amos 3:7",
      "text": "Surely the Lord GOD will do nothing, but he revealeth his secret unto his servants the prophets."
    }
  ],
  "61": [
    {
      "ref": "Ephesians 2:19",
      "text": "Now therefore ye are no more strangers and foreigners, but fellowcitizens with the saints, and of the household of God;"
    },
    {
      "ref": "Ephesians 2:20",
      "text": "And are built upon the foundation of the apostles and prophets, Jesus Christ himself being the chief corner stone;"
    }
  ],
  "62": [
    {
      "ref": "Ephesians 4:11",
      "text": "And he gave some, apostles; and some, prophets; and some, evangelists; and some, pastors and teachers;"
    },
    {
      "ref": "Ephesians 4:12",
      "text": "For the perfecting of the saints, for the work of the ministry, for the edifying of the body of Christ:"
    },
    {
      "ref": "Ephesians 4:13",
      "text": "Till we all come in the unity of the faith, and of the knowledge of the Son of God, unto a perfect man, unto the measure of the stature of the fulness of Christ:"
    },
    {
      "ref": "Ephesians 4:14",
      "text": "That we henceforth be no more children, tossed to and fro, and carried about with every wind of doctrine, by the sleight of men, and cunning craftiness, whereby they lie in wait to deceive;"
    }
  ],
  "63": [
    {
      "ref": "1 Corinthians 8:5",
      "text": "For though there be that are called gods, whether in heaven or in earth, (as there be gods many, and lords many,)"
    },
    {
      "ref": "1 Corinthians 8:6",
      "text": "But to us there is but one God, the Father, of whom are all things, and we in him; and one Lord Jesus Christ, by whom are all things, and we by him."
    }
  ],
  "64": [
    {
      "ref": "John 14:28",
      "text": "Ye have heard how I said unto you, I go away, and come again unto you. If ye loved me, ye would rejoice, because I said, I go unto the Father: for my Father is greater than I."
    }
  ],
  "65": [
    {
      "ref": "1 Corinthians 15:40",
      "text": "There are also celestial bodies, and bodies terrestrial: but the glory of the celestial is one, and the glory of the terrestrial is another."
    },
    {
      "ref": "1 Corinthians 15:41",
      "text": "There is one glory of the sun, and another glory of the moon, and another glory of the stars: for one star differeth from another star in glory."
    },
    {
      "ref": "1 Corinthians 15:42",
      "text": "So also is the resurrection of the dead. It is sown in corruption; it is raised in incorruption:"
    }
  ],
  "66": [
    {
      "ref": "John 5:19",
      "text": "Then answered Jesus and said unto them, Verily, verily, I say unto you, The Son can do nothing of himself, but what he seeth the Father do: for what things soever he doeth, these also doeth the Son likewise."
    }
  ],
  "67": [
    {
      "ref": "Revelation 20:12",
      "text": "And I saw the dead, small and great, stand before God; and the books were opened: and another book was opened, which is the book of life: and the dead were judged out of those things which were written in the books, according to their works."
    }
  ],
  "68": [
    {
      "ref": "1 Peter 3:18",
      "text": "For Christ also hath once suffered for sins, the just for the unjust, that he might bring us to God, being put to death in the flesh, but quickened by the Spirit:"
    },
    {
      "ref": "1 Peter 3:19",
      "text": "By which also he went and preached unto the spirits in prison;"
    },
    {
      "ref": "1 Peter 3:20",
      "text": "Which sometime were disobedient, when once the longsuffering of God waited in the days of Noah, while the ark was a preparing, wherein few, that is, eight souls were saved by water."
    }
  ],
  "69": [
    {
      "ref": "1 Peter 4:6",
      "text": "For for this cause was the gospel preached also to them that are dead, that they might be judged according to men in the flesh, but live according to God in the spirit."
    }
  ],
  "70": [
    {
      "ref": "John 3:5",
      "text": "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God."
    }
  ],
  "71": [
    {
      "ref": "Matthew 16:18",
      "text": "And I say also unto thee, That thou art Peter, and upon this rock I will build my church; and the gates of hell shall not prevail against it."
    },
    {
      "ref": "Matthew 16:19",
      "text": "And I will give unto thee the keys of the kingdom of heaven: and whatsoever thou shalt bind on earth shall be bound in heaven: and whatsoever thou shalt loose on earth shall be loosed in heaven."
    }
  ],
  "72": [
    {
      "ref": "Acts 3:20",
      "text": "And he shall send Jesus Christ, which before was preached unto you:"
    },
    {
      "ref": "Acts 3:21",
      "text": "Whom the heaven must receive until the times of restitution of all things, which God hath spoken by the mouth of all his holy prophets since the world began."
    }
  ],
  "73": [
    {
      "ref": "Malachi 4:5",
      "text": "Behold, I will send you Elijah the prophet before the coming of the great and dreadful day of the LORD:"
    },
    {
      "ref": "Malachi 4:6",
      "text": "And he shall turn the heart of the fathers to the children, and the heart of the children to their fathers, lest I come and smite the earth with a curse."
    }
  ],
  "74": [
    {
      "ref": "John 10:16",
      "text": "And other sheep I have, which are not of this fold: them also I must bring, and they shall hear my voice; and there shall be one fold, and one shepherd."
    }
  ],
  "75": [
    {
      "ref": "Ezekiel 37:15",
      "text": "The word of the LORD came again unto me, saying,"
    },
    {
      "ref": "Ezekiel 37:16",
      "text": "Moreover, thou son of man, take thee one stick, and write upon it, For Judah, and for the children of Israel his companions: then take another stick, and write upon it, For Joseph, the stick of Ephraim, and for all the house of Israel his companions:"
    },
    {
      "ref": "Ezekiel 37:17",
      "text": "And join them one to another into one stick; and they shall become one in thine hand."
    }
  ],
  "76": [
    {
      "ref": "Isaiah 29:4",
      "text": "And thou shalt be brought down, and shalt speak out of the ground, and thy speech shall be low out of the dust, and thy voice shall be, as of one that hath a familiar spirit, out of the ground, and thy speech shall whisper out of the dust."
    }
  ],
  "77": [
    {
      "ref": "Isaiah 29:11",
      "text": "And the vision of all is become unto you as the words of a book that is sealed, which men deliver to one that is learned, saying, Read this, I pray thee: and he saith, I cannot; for it is sealed:"
    },
    {
      "ref": "Isaiah 29:12",
      "text": "And the book is delivered to him that is not learned, saying, Read this, I pray thee: and he saith, I am not learned."
    },
    {
      "ref": "Isaiah 29:13",
      "text": "Wherefore the Lord said, Forasmuch as this people draw near me with their mouth, and with their lips do honour me, but have removed their heart far from me, and their fear toward me is taught by the precept of men:"
    },
    {
      "ref": "Isaiah 29:14",
      "text": "Therefore, behold, I will proceed to do a marvellous work among this people, even a marvellous work and a wonder: for the wisdom of their wise men shall perish, and the understanding of their prudent men shall be hid."
    }
  ],
  "78": [
    {
      "ref": "James 2:17",
      "text": "Even so faith, if it hath not works, is dead, being alone."
    },
    {
      "ref": "James 2:18",
      "text": "Yea, a man may say, Thou hast faith, and I have works: shew me thy faith without thy works, and I will shew thee my faith by my works."
    }
  ],
  "79": [
    {
      "ref": "Revelation 14:6",
      "text": "And I saw another angel fly in the midst of heaven, having the everlasting gospel to preach unto them that dwell on the earth, and to every nation, and kindred, and tongue, and people,"
    },
    {
      "ref": "Revelation 14:7",
      "text": "Saying with a loud voice, Fear God, and give glory to him; for the hour of his judgment is come: and worship him that made heaven, and earth, and the sea, and the fountains of waters."
    }
  ],
  "80": [
    {
      "ref": "Hebrews 5:4",
      "text": "And no man taketh this honour unto himself, but he that is called of God, as was Aaron."
    }
  ],
  "81": [
    {
      "ref": "John 15:16",
      "text": "Ye have not chosen me, but I have chosen you, and ordained you, that ye should go and bring forth fruit, and that your fruit should remain: that whatsoever ye shall ask of the Father in my name, he may give it you."
    }
  ],
  "82": [
    {
      "ref": "Matthew 7:21",
      "text": "Not every one that saith unto me, Lord, Lord, shall enter into the kingdom of heaven; but he that doeth the will of my Father which is in heaven."
    }
  ],
  "83": [
    {
      "ref": "1 Corinthians 12:13",
      "text": "For by one Spirit are we all baptized into one body, whether we be Jews or Gentiles, whether we be bond or free; and have been all made to drink into one Spirit."
    },
    {
      "ref": "1 Corinthians 12:14",
      "text": "For the body is not one member, but many."
    },
    {
      "ref": "1 Corinthians 12:15",
      "text": "If the foot shall say, Because I am not the hand, I am not of the body; is it therefore not of the body?"
    },
    {
      "ref": "1 Corinthians 12:16",
      "text": "And if the ear shall say, Because I am not the eye, I am not of the body; is it therefore not of the body?"
    },
    {
      "ref": "1 Corinthians 12:17",
      "text": "If the whole body were an eye, where were the hearing? If the whole were hearing, where were the smelling?"
    },
    {
      "ref": "1 Corinthians 12:18",
      "text": "But now hath God set the members every one of them in the body, as it hath pleased him."
    },
    {
      "ref": "1 Corinthians 12:19",
      "text": "And if they were all one member, where were the body?"
    },
    {
      "ref": "1 Corinthians 12:20",
      "text": "But now are they many members, yet but one body."
    },
    {
      "ref": "1 Corinthians 12:21",
      "text": "And the eye cannot say unto the hand, I have no need of thee: nor again the head to the feet, I have no need of you."
    },
    {
      "ref": "1 Corinthians 12:22",
      "text": "Nay, much more those members of the body, which seem to be more feeble, are necessary:"
    },
    {
      "ref": "1 Corinthians 12:23",
      "text": "And those members of the body, which we think to be less honourable, upon these we bestow more abundant honour; and our uncomely parts have more abundant comeliness."
    },
    {
      "ref": "1 Corinthians 12:24",
      "text": "For our comely parts have no need: but God hath tempered the body together, having given more abundant honour to that part which lacked:"
    },
    {
      "ref": "1 Corinthians 12:25",
      "text": "That there should be no schism in the body; but that the members should have the same care one for another."
    },
    {
      "ref": "1 Corinthians 12:26",
      "text": "And whether one member suffer, all the members suffer with it; or one member be honoured, all the members rejoice with it."
    },
    {
      "ref": "1 Corinthians 12:27",
      "text": "Now ye are the body of Christ, and members in particular."
    }
  ],
  "84": [
    {
      "ref": "Acts 2:38",
      "text": "Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost."
    },
    {
      "ref": "Acts 2:39",
      "text": "For the promise is unto you, and to your children, and to all that are afar off, even as many as the Lord our God shall call."
    }
  ],
  "85": [
    {
      "ref": "Mark 16:15",
      "text": "And he said unto them, Go ye into all the world, and preach the gospel to every creature."
    },
    {
      "ref": "Mark 16:16",
      "text": "He that believeth and is baptized shall be saved; but he that believeth not shall be damned."
    },
    {
      "ref": "Mark 16:17",
      "text": "And these signs shall follow them that believe; In my name shall they cast out devils; they shall speak with new tongues;"
    },
    {
      "ref": "Mark 16:18",
      "text": "They shall take up serpents; and if they drink any deadly thing, it shall not hurt them; they shall lay hands on the sick, and they shall recover."
    }
  ],
  "86": [
    {
      "ref": "Hebrews 6:1",
      "text": "Therefore leaving the principles of the doctrine of Christ, let us go on unto perfection; not laying again the foundation of repentance from dead works, and of faith toward God,"
    },
    {
      "ref": "Hebrews 6:2",
      "text": "Of the doctrine of baptisms, and of laying on of hands, and of resurrection of the dead, and of eternal judgment."
    }
  ],
  "87": [
    {
      "ref": "Acts 8:14",
      "text": "Now when the apostles which were at Jerusalem heard that Samaria had received the word of God, they sent unto them Peter and John:"
    },
    {
      "ref": "Acts 8:15",
      "text": "Who, when they were come down, prayed for them, that they might receive the Holy Ghost:"
    },
    {
      "ref": "Acts 8:16",
      "text": "(For as yet he was fallen upon none of them: only they were baptized in the name of the Lord Jesus.)"
    },
    {
      "ref": "Acts 8:17",
      "text": "Then laid they their hands on them, and they received the Holy Ghost."
    }
  ],
  "88": [
    {
      "ref": "Romans 6:3",
      "text": "Know ye not, that so many of us as were baptized into Jesus Christ were baptized into his death?"
    },
    {
      "ref": "Romans 6:4",
      "text": "Therefore we are buried with him by baptism into death: that like as Christ was raised up from the dead by the glory of the Father, even so we also should walk in newness of life."
    },
    {
      "ref": "Romans 6:5",
      "text": "For if we have been planted together in the likeness of his death, we shall be also in the likeness of his resurrection:"
    }
  ],
  "89": [
    {
      "ref": "1 Corinthians 11:11",
      "text": "Nevertheless neither is the man without the woman, neither the woman without the man, in the Lord."
    }
  ],
  "90": [
    {
      "ref": "Genesis 1:26",
      "text": "And God said, Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the fowl of the air, and over the cattle, and over all the earth, and over every creeping thing that creepeth upon the earth."
    },
    {
      "ref": "Genesis 1:27",
      "text": "So God created man in his own image, in the image of God created he him; male and female created he them."
    }
  ],
  "91": [
    {
      "ref": "Revelation 1:6",
      "text": "And hath made us kings and priests unto God and his Father; to him be glory and dominion for ever and ever. Amen."
    }
  ],
  "92": [
    {
      "ref": "Revelation 5:10",
      "text": "And hast made us unto our God kings and priests: and we shall reign on the earth."
    }
  ],
  "93": [
    {
      "ref": "John 21:25",
      "text": "And there are also many other things which Jesus did, the which, if they should be written every one, I suppose that even the world itself could not contain the books that should be written. Amen."
    }
  ],
  "94": [
    {
      "ref": "John 16:12",
      "text": "I have yet many things to say unto you, but ye cannot bear them now."
    },
    {
      "ref": "John 16:13",
      "text": "Howbeit when he, the Spirit of truth, is come, he will guide you into all truth: for he shall not speak of himself; but whatsoever he shall hear, that shall he speak: and he will shew you things to come."
    }
  ],
  "95": [
    {
      "ref": "Amos 8:11",
      "text": "Behold, the days come, saith the Lord GOD, that I will send a famine in the land, not a famine of bread, nor a thirst for water, but of hearing the words of the LORD:"
    },
    {
      "ref": "Amos 8:12",
      "text": "And they shall wander from sea to sea, and from the north even to the east, they shall run to and fro to seek the word of the LORD, and shall not find it."
    }
  ],
  "96": [
    {
      "ref": "Isaiah 24:5",
      "text": "The earth also is defiled under the inhabitants thereof; because they have transgressed the laws, changed the ordinance, broken the everlasting covenant."
    }
  ],
  "97": [
    {
      "ref": "2 Thessalonians 2:1",
      "text": "Now we beseech you, brethren, by the coming of our Lord Jesus Christ, and by our gathering together unto him,"
    },
    {
      "ref": "2 Thessalonians 2:2",
      "text": "That ye be not soon shaken in mind, or be troubled, neither by spirit, nor by word, nor by letter as from us, as that the day of Christ is at hand."
    },
    {
      "ref": "2 Thessalonians 2:3",
      "text": "Let no man deceive you by any means: for that day shall not come, except there come a falling away first, and that man of sin be revealed, the son of perdition;"
    }
  ],
  "98": [
    {
      "ref": "Acts 20:29",
      "text": "For I know this, that after my departing shall grievous wolves enter in among you, not sparing the flock."
    },
    {
      "ref": "Acts 20:30",
      "text": "Also of your own selves shall men arise, speaking perverse things, to draw away disciples after them."
    }
  ],
  "99": [
    {
      "ref": "Daniel 2:44",
      "text": "And in the days of these kings shall the God of heaven set up a kingdom, which shall never be destroyed: and the kingdom shall not be left to other people, but it shall break in pieces and consume all these kingdoms, and it shall stand for ever."
    }
  ],
  "100": [
    {
      "ref": "Matthew 5:48",
      "text": "Be ye therefore perfect, even as your Father which is in heaven is perfect."
    }
  ]
};

export function kjvVersesFor(id: number): KjvVerse[] | undefined {
  return KJV_TEXT[id];
}
