// Sync Cameron's review board (Firestore "reviews") into the git repo so the
// build machines can see it. Uses the admin service account (bypasses rules).
//   node admin/sync-reviews.mjs
// Writes:
//   media-production/approvals.json  — {num: {hash, date}} for videos Cameron
//     approved AND whose current cut still matches (version-locked).
//   media-production/COMPLAINTS.md   — active complaints (about the current cut),
//     the machine-readable "what to fix" list.
// It does NOT commit/push — the caller does that.
import admin from 'firebase-admin';
import { readFileSync, writeFileSync } from 'fs';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const here = dirname(fileURLToPath(import.meta.url));
const REPO = join(here, '..');
const sa = JSON.parse(readFileSync(join(here, 'serviceAccount.json'), 'utf8'));
admin.initializeApp({ credential: admin.credential.cert(sa) });
const db = admin.firestore();

// current git blob hash of every finished mp4 -> {num: hash}
const hashes = {};
execSync('git ls-tree -r HEAD -- media-production', { cwd: REPO }).toString()
  .split('\n').forEach((line) => {
    const [meta, path] = line.split('\t');
    if (!path) return;
    const h = (meta || '').split(/\s+/)[2];
    const m = path.match(/media-production\/build-(\d+)-.*\/[0-9a-z]+-\d+_.*\.mp4$/);
    if (m) hashes[+m[1]] = h;
  });

const snap = await db.collection('reviews').get();
const approvals = {};
const complaints = [];
snap.forEach((doc) => {
  const n = doc.id;
  const d = doc.data();
  const cur = hashes[+n];
  const day = d.approvedAt && d.approvedAt.toDate
    ? d.approvedAt.toDate().toISOString().slice(0, 10) : '';
  if (d.approved && d.approvedHash && d.approvedHash === cur) {
    approvals[n] = { hash: d.approvedHash, date: day };
  }
  if (d.complaint && d.complaintHash && d.complaintHash === cur) {
    complaints.push({ num: +n, text: d.complaint });
  }
});

writeFileSync(
  join(REPO, 'media-production', 'approvals.json'),
  JSON.stringify(approvals, Object.keys(approvals).sort((a, b) => +a - +b), 2) + '\n');

complaints.sort((a, b) => a.num - b.num);
let md = '# ACTIVE COMPLAINTS — Cameron flagged these from the review page\n\n';
md += 'Auto-generated by `admin/sync-reviews.mjs` from the review board. Each row is a\n';
md += 'problem on the CURRENT cut of that video. Fix it, rebuild, push — the complaint\n';
md += 'clears itself once a newer cut replaces the video. Do NOT edit by hand.\n\n';
md += '| # | What Cameron said |\n|---|---|\n';
if (complaints.length === 0) md += '| — | (none right now) |\n';
for (const c of complaints) md += `| ${c.num} | ${c.text.replace(/\n/g, ' ').replace(/\|/g, '/')} |\n`;
writeFileSync(join(REPO, 'media-production', 'COMPLAINTS.md'), md);

console.log(`synced: ${Object.keys(approvals).length} approved, ${complaints.length} active complaints`);
process.exit(0);
