// Sync Cameron's review board (Firestore "reviews") into the git repo so the
// build machines can see it. Uses the admin service account (bypasses rules).
//   node admin/sync-reviews.mjs
// Writes:
//   media-production/approvals.json  — {num: {hash, date}} for videos Cameron
//     approved AND whose current cut still matches (version-locked).
//   media-production/COMPLAINTS.md   — active complaints (about the current cut),
//     the machine-readable "what to fix" list.
// It does NOT commit/push — the caller does that.
import admin from 'firebase-admin';
import { readFileSync, writeFileSync } from 'fs';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const here = dirname(fileURLToPath(import.meta.url));
const REPO = join(here, '..');
const sa = JSON.parse(readFileSync(join(here, 'serviceAccount.json'), 'utf8'));
admin.initializeApp({ credential: admin.credential.cert(sa) });
const db = admin.firestore();

function numericKeyOrder(obj) {
  return Object.fromEntries(
    Object.keys(obj).sort((a, b) => +a - +b).map((key) => [key, obj[key]]));
}

// current git blob hash of every finished mp4 -> {num: hash}
const hashes = {};
// maxBuffer: the repo outgrew execSync's default 1 MB and this threw ENOBUFS,
// which crashed the sync — so the board stopped reporting new denials at all
// and the lookout was running blind (2026-07-18).
execSync('git ls-tree -r HEAD -- media-production',
         { cwd: REPO, maxBuffer: 512 * 1024 * 1024 }).toString()
  .split('\n').forEach((line) => {
    const [meta, path] = line.split('\t');
    if (!path) return;
    const h = (meta || '').split(/\s+/)[2];
    const m = path.match(/media-production\/build-(\d+)-.*\/[0-9a-z]+-\d+_.*\.mp4$/);
    if (m) hashes[+m[1]] = h;
  });

// The review page can point at a newer, reviewer-only candidate without
// replacing the app's current media. Those cards are the source of truth for
// this review wave, so their version-lock hashes override the app-media hashes.
const reviewHtml = readFileSync(join(REPO, 'site', 'review.html'), 'utf8');
const reviewCard = /<div class="card"[^>]*data-num="(\d+)"[^>]*data-hash="([0-9a-f]+)"[^>]*data-review-wave="realistic-v2"[^>]*>/g;
for (const match of reviewHtml.matchAll(reviewCard)) {
  hashes[+match[1]] = match[2];
}

const snap = await db.collection('reviews').get();
const approvals = {};
const complaints = [];
const reviewLessons = {};
snap.forEach((doc) => {
  const n = doc.id;
  const d = doc.data();
  const cur = hashes[+n];
  const day = d.approvedAt && d.approvedAt.toDate
    ? d.approvedAt.toDate().toISOString().slice(0, 10) : '';
  if (d.approved && d.approvedHash && d.approvedHash === cur) {
    approvals[n] = { hash: d.approvedHash, date: day };
  }
  // A complaint stays ACTIVE until Cameron approves the video — full stop.
  // The old rule (complaintHash === current hash) silently dropped a complaint
  // the moment ANY newer cut shipped, even when that cut fixed something else
  // entirely; Cameron re-watched videos on 2026-07-21 and found defects he had
  // complained about weeks-old and "cleared". Only his approval clears it now.
  // A hash mismatch just means a newer cut shipped SINCE the complaint — flag
  // it so the fixer re-verifies the complaint against the current cut.
  const complaintOpen = typeof d.complaintOpen === 'boolean'
    ? d.complaintOpen : !!(d.complaint && !d.approved);
  if (d.complaint) {
    const history = Array.isArray(d.complaintHistory)
      ? d.complaintHistory.map((item) => ({
          text: String(item.text || ''),
          hash: item.hash || null,
          createdAt: item.createdAt || null,
        })).filter((item) => item.text)
      : [];
    if (!history.some((item) => item.text === d.complaint
        && item.hash === (d.complaintHash || null))) {
      history.push({
        text: d.complaint,
        hash: d.complaintHash || null,
        createdAt: d.complaintAt && d.complaintAt.toDate
          ? d.complaintAt.toDate().toISOString() : null,
      });
    }
    reviewLessons[n] = {
      open: complaintOpen,
      latest: d.complaint,
      reportedAgainst: d.complaintHash || null,
      resolvedBy: complaintOpen ? null
        : (d.complaintResolvedHash || (d.approved ? d.approvedHash : null) || null),
      history,
    };
  }
  if (d.complaint && complaintOpen) {
    const shippedSince = d.complaintHash && d.complaintHash !== cur;
    complaints.push({ num: +n, text: d.complaint, shippedSince });
  }
});

writeFileSync(
  join(REPO, 'media-production', 'approvals.json'),
  JSON.stringify(numericKeyOrder(approvals), null, 2) + '\n');

complaints.sort((a, b) => a.num - b.num);
let md = '# ACTIVE COMPLAINTS — Cameron flagged these from the review page\n\n';
md += 'Auto-generated by `admin/sync-reviews.mjs` from the review board. Each row is a\n';
md += 'problem Cameron reported that he has NOT yet approved away. A complaint only\n';
md += 'clears when Cameron APPROVES the video — shipping a new cut does not clear it\n';
md += '(rule changed 2026-07-21 after fixes for other defects silently "cleared"\n';
md += 'unfixed complaints). "newer cut shipped" means someone shipped since he\n';
md += 'complained — VERIFY the complaint is truly fixed in the CURRENT cut before\n';
md += 'touching anything else. Do NOT edit by hand.\n\n';
md += '| # | Status | What Cameron said |\n|---|---|---|\n';
if (complaints.length === 0) md += '| — | — | (none right now) |\n';
for (const c of complaints) {
  const st = c.shippedSince ? 'newer cut shipped — VERIFY fixed' : 'UNFIXED';
  md += `| ${c.num} | ${st} | ${c.text.replace(/\n/g, ' ').replace(/\|/g, '/')} |\n`;
}
writeFileSync(join(REPO, 'media-production', 'COMPLAINTS.md'), md);
writeFileSync(
  join(REPO, 'media-production-v2', 'REVIEW-LESSONS.json'),
  JSON.stringify(numericKeyOrder(reviewLessons), null, 2) + '\n');

console.log(`synced: ${Object.keys(approvals).length} approved, ${complaints.length} active complaints, ${Object.keys(reviewLessons).length} retained review lessons`);
process.exit(0);
