#!/usr/bin/env python3
"""V2 beat map — row 120, build-120-job-from-whirlwind (SCRIPTURE REFERENCE — FILL IN).

SCAFFOLD generated by v2_scaffold.py. Runtime 241.8 s, 42 pictures (5.8 s each).
The windows, segment labels, ids and filenames below are correct and
checked. EVERYTHING ELSE IS YOURS TO WRITE, and the row will not pass
v2_prompt.py --check until you have written it.

BEFORE YOU WRITE A SINGLE SCENE:
  1. Read the KJV passage in full and put the facts that govern the
     pictures in this header — direction, position, scale, time of day.
  2. Check media-production/CONTENT-CARE.md §3 for this row's flags.
  3. Decide the time-of-day arc and state it here, so no later QC pass
     mistakes a correct sunset for the row-11 storm defect.
  4. Name any prop or condition that CHANGES across the row (a cloak, a
     posture, an illness) and keep it OUT of the locks — a lock must
     never contradict a beat.
"""

# LOCKS: one entry per recurring person and per setting. Setting locks must
# NEVER name a character (the STRAY-JESUS defect). State clothing colours
# POSITIVELY and dark — 'never cream' alone does not hold. Only Jesus wears
# cream. Recurring cast (PETER, ANDREW, JOHN, JAMES-Z) come from the shared
# CAST_LOCKS in v2_prompt.py — do not redefine them here.
LOCKS = {
    # "NAME": (
    #     "NAME LOCK: ..."
    # ),
}

REF = True

# Deliberately contains the banned phrase so v2_prompt.py --check FAILS this
# row until every scene below is written by hand. Do not soften it.
SCENE_TODO = ("SCENE_TODO — unwritten scene. Contains a NEGATIVE PROMPT "
              "marker so the v4 checker rejects this row until replaced.")

BEATS = [
    {
        "id": "v2-r120-b01", "out": "s01-job-was-a-good-man.jpeg", "seg": "n1",
        "window": "0.28-9.14", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "Job was a good man — honest, generous, devoted to God — and for "
            "most of his life that goodness and a happy, prosperous home went "
            "together."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b02", "out": "s02-then-they-started-explaining.jpeg", "seg": "n4",
        "window": "70.06-71.89", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "Then they started explaining.",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b03", "out": "s03-and-then-in-a-single.jpeg", "seg": "n2",
        "window": "9.71-13.88", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "And then, in a single devastating stretch, it was all taken.",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b04", "out": "s04-one-of-the-oldest-hardest.jpeg", "seg": "n2",
        "window": "18.60-25.96", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "One of the oldest, hardest questions in the world landed on the "
            "best man in it: why do good people suffer?"
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b05", "out": "s05-and-this-is-what-he.jpeg", "seg": "n2",
        "window": "25.96-29.30", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "And this is what he said on the day it happened.",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b06", "out": "s06-naked-came-i-out-of.jpeg", "seg": "s121",
        "window": "29.86-38.53", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "Naked came I out of my mother's womb, and naked shall I return "
            "thither: the LORD gave, and the LORD hath taken away; blessed be "
            "the name of the LORD."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b07", "out": "s07-i-have-said-my-piece.jpeg", "seg": "n7",
        "window": "195.06-198.51", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "I have said my piece and I will not say it again.",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b08", "out": "s08-i-came-into-this-world.jpeg", "seg": "n2b",
        "window": "40.08-47.67", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "I came into this world with nothing and I will leave with nothing. "
            "God gave it and God has taken it, and I will bless him anyway."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b09", "out": "s09-he-is-not-calm-when.jpeg", "seg": "n2b",
        "window": "47.67-52.23", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "He is not calm when he says it. He has just torn his coat and "
            "shaved his head."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b10", "out": "s10-he-is-wrecked-and-still.jpeg", "seg": "n2b + n3",
        "window": "52.23-59.88", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "He is wrecked, and still holding on. He sat down in the ashes, "
            "sick and broken, and he did not pretend to be all right."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b11", "out": "s11-he-grieved-out-loud-and.jpeg", "seg": "n3",
        "window": "59.88-63.70", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "He grieved out loud. And scripture never once scolds him for it.",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b12", "out": "s12-his-friends-came-and-at.jpeg", "seg": "n4",
        "window": "64.24-70.06", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "His friends came, and at first they simply sat with him — which "
            "was the best thing they did."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b13", "out": "s13-you-must-have-sinned-they.jpeg", "seg": "n4",
        "window": "71.89-75.44", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "You must have sinned, they said. This must be your fault.",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b14", "out": "s14-their-tidy-answers-only-deepened.jpeg", "seg": "n4 + n5",
        "window": "75.44-82.38", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "Their tidy answers only deepened the wound. But Job would not "
            "accept easy lies about God or about himself."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b15", "out": "s15-he-did-something-braver-than.jpeg", "seg": "n5",
        "window": "82.38-84.75", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "He did something braver than pretending.",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b16", "out": "s16-he-took-his-anguish-straight.jpeg", "seg": "n5",
        "window": "84.75-90.99", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "He took his anguish straight to God and demanded an answer — and "
            "then, in the middle of it, he said this."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b17", "out": "s17-for-i-know-that-my.jpeg", "seg": "s1925",
        "window": "91.50-96.54", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "For I know that my redeemer liveth, and that he shall stand at the "
            "latter day upon the earth."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b18", "out": "s18-that-is-a-man-in.jpeg", "seg": "n5b",
        "window": "97.98-102.09", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "That is a man in the ashes with nothing left, saying it out loud.",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b19", "out": "s19-he-does-not-understand-a.jpeg", "seg": "n5b",
        "window": "102.09-107.77", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "He does not understand a thing that is happening to him, and he "
            "still knows who is coming."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b20", "out": "s20-and-god-answered-though-not.jpeg", "seg": "n6",
        "window": "108.31-115.73", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "And God answered — though not in the way anyone expected. Out of a "
            "great whirlwind, the Maker of everything finally spoke."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b21", "out": "s21-where-wast-thou-when-i.jpeg", "seg": "jvA",
        "window": "116.26-120.40", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "Where wast thou when I laid the foundations of the earth?",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b22", "out": "s22-declare-if-thou-hast-understanding.jpeg", "seg": "jvA + n6b",
        "window": "120.40-126.94", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "declare, if thou hast understanding. It sounds like a rebuke, and "
            "it is not."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b23", "out": "s23-god-is-doing-something-gentler.jpeg", "seg": "n6b",
        "window": "126.94-129.48", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "God is doing something gentler than that.",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b24", "out": "s24-he-is-taking-a-man.jpeg", "seg": "n6b",
        "window": "129.48-135.48", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "He is taking a man who has shrunk down to the size of his own "
            "pain, and slowly widening the room."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b25", "out": "s25-when-the-morning-stars-sang.jpeg", "seg": "jv387",
        "window": "136.04-141.50", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "When the morning stars sang together, and all the sons of God "
            "shouted for joy."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b26", "out": "s26-that-is-god-describing-the.jpeg", "seg": "n7a",
        "window": "143.03-148.65", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "That is God describing the day the world was made — and it is not "
            "a lecture about power."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b27", "out": "s27-it-is-a-memory-and.jpeg", "seg": "n7a + jvB",
        "window": "148.65-157.92", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "It is a memory, and it is full of gladness. Canst thou bind the "
            "sweet influences of Pleiades, or loose the bands of Orion?"
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b28", "out": "s28-i-had-only-ever-heard.jpeg", "seg": "n7c",
        "window": "217.31-219.99", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "I had only ever heard about you, Job says.",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b29", "out": "s29-can-you-tie-up-the.jpeg", "seg": "n7b",
        "window": "159.41-168.82", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "Can you tie up the Pleiades, God asks, or unfasten Orion's belt? "
            "On and on it goes — the sea, the snow, the wild donkey, the horse, "
            "the hawk."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b30", "out": "s30-his-wealth-his-health-and.jpeg", "seg": "n2",
        "window": "13.88-18.60", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "His wealth, his health, and — most unbearable of all — his "
            "children."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b31", "out": "s31-chapter-after-chapter-of-a.jpeg", "seg": "n7b",
        "window": "168.82-177.09", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "Chapter after chapter of a world far bigger and stranger and "
            "kinder than the tidy little courtroom Job's friends had built."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b32", "out": "s32-behold-i-am-vile-what.jpeg", "seg": "s404",
        "window": "177.59-182.92", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "Behold, I am vile; what shall I answer thee? I will lay mine hand "
            "upon my mouth."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b33", "out": "s33-once-have-i-spoken-but.jpeg", "seg": "s404",
        "window": "182.92-188.64", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "Once have I spoken; but I will not answer: yea, twice; but I will "
            "proceed no further."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b34", "out": "s34-i-have-nothing-to-say.jpeg", "seg": "n7",
        "window": "190.14-195.06", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "I have nothing to say, Job answers. I am putting my hand over my "
            "mouth."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b35", "out": "s35-not-beaten-quieted-god-never.jpeg", "seg": "n7",
        "window": "198.51-201.67", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "Not beaten — quieted. God never explained why.",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b36", "out": "s36-instead-he-showed-job-the.jpeg", "seg": "n7",
        "window": "201.67-209.47", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "Instead he showed Job the sea and the stars and the wild goodness "
            "of a world Job could never have made or held."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b37", "out": "s37-and-somehow-it-was-enough.jpeg", "seg": "n7",
        "window": "209.47-211.30", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "And somehow it was enough.",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b38", "out": "s38-i-have-heard-of-thee.jpeg", "seg": "s425",
        "window": "211.85-215.79", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "I have heard of thee by the hearing of the ear: but now mine eye "
            "seeth thih."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b39", "out": "s39-now-i-have-seen-you.jpeg", "seg": "n7c",
        "window": "219.99-223.56", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "Now I have seen you with my own eyes. That is the ending.",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b40", "out": "s40-not-because-he-got-his.jpeg", "seg": "n7c",
        "window": "223.56-227.52", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": "Not because he got his answer, but because he got God himself.",
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b41", "out": "s41-the-suffering-was-never-fully.jpeg", "seg": "n8",
        "window": "227.96-234.45", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "The suffering was never fully explained — not to Job, and not to "
            "us. But Job was no longer alone in it."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
    {
        "id": "v2-r120-b42", "out": "s42-the-god-he-thought-had.jpeg", "seg": "n8",
        "window": "234.45-241.52", "wide": True, "jesus": False, "ref": False,
        "locks": [],
        "narration": (
            "The God he thought had abandoned him had come near, and that "
            "nearness was the answer his grief actually needed."
        ),
        "must_show": "TODO",
        "must_not_show": "TODO — always include: no halo, glare or rim-light on Jesus.",
        "scene": SCENE_TODO,
    },
]
