#!/usr/bin/env python3
"""Assemble Story Video #43 — The Wedding Garment (Matthew 22:1-14).

PHASE-1 STILLS-ONLY build (Law E): 14 painted stills with slow Ken Burns drift,
narration, serif captions, cream-italic KJV lines, closing question card. NO AI
motion clips.

Stills live in assets/<slug>.jpeg. In "old faithful" mode they come from the Google
Flow browser burst; the same files also work if generated by gen_stills.py. build.py
does not care which made them — it only reads assets/<slug>.jpeg.

CAPTIONS ARE VERBATIM: every caption is the exact spoken text of its narration
segment (imported from make_narration.SEGMENTS and word-wrapped). KJV (Jesus)
lines render in cream italic.

Face-never (the #1 Law): Jesus appears in exactly two stills (s1, s13), both with the
camera behind him — the back of his head to us, face never rendered. Verses 2-13 are
the parable he is TELLING, so no divine figure appears in any parable still; the king,
the servants and the guests are ordinary people with faces fully shown. The KING is a
character in the parable, NOT a depiction of God — face shown, dressed royal purple so
he never reads as a second Jesus.

CARE FLAGS J, L. The two sacred silences land on the two MERCY beats, never on the
judgment — the J-law forbids spotlighting outer darkness. jv13 (outer darkness) plays
UNDER a soft moving bed on purpose, so it is passed through rather than enshrined.

TWO SACRED SILENCES (the music bed dies to true silence for both):
  jv8_9  Matt 22:8-9   "...Go ye therefore into the highways..."  — THE GRACE PIVOT,
                       the doors thrown open to everyone (verse-card / PAIRING-LIST)
  jv12   Matt 22:12    "Friend, how camest thou in hither..."     — THE TENDER PIVOT,
                       the king calls the excluded man "Friend"
A warm bed carries the story in, dies before the grace pivot, returns to carry the
gathering, dies again before "Friend", then returns to carry the outer-darkness
resolution, the frame, and the closing invitation. No-Dead-Air is unaffected — the
narrator never stops; only the music does.

Timing is COMPUTED from measured mp3 durations, and every beat is timed off the
SPOKEN end of its audio, never the file end. The build RAISES on any spoken gap
over 2.5s so a No-Dead-Air violation cannot ship (the #39 lesson).

Output: matthew-22_wedding-garment.mp4 (SCRIPTURE-NAME LAW),
1080x1920 H.264 30fps, <25MB.
"""
import os
import subprocess
import textwrap

import make_narration  # SEGMENTS -> verbatim caption text per segment

A = "assets"         # gen_stills.py writes <slug>.jpeg here
S = "segs"
FPS = 30
FF = "ffmpeg"
FPROBE = "ffprobe"
SERIF = "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf"
SERIF_BI = "/usr/share/fonts/truetype/liberation/LiberationSerif-Italic.ttf"
CREAM = "0xF7F2E9"
INK = "0x3B2A1E"

ENC = ["-c:v", "libx264", "-preset", "medium", "-crf", "16",
       "-pix_fmt", "yuv420p", "-r", str(FPS), "-an"]

S1 = "s1-on-the-hillside.jpeg"
S2 = "s2-both-men-heard.jpeg"
S3 = "s3-digging-to-the-rock.jpeg"
S4 = "s4-founded-on-the-rock.jpeg"
S5 = "s5-the-house-on-the-rock.jpeg"
S6 = "s6-it-fell-not.jpeg"
S7 = "s7-building-on-the-sand.jpeg"
S8 = "s8-the-house-on-the-sand.jpeg"
S9 = "s9-great-was-the-fall.jpeg"
S10 = "s10-the-morning-after.jpeg"
S11 = "s11-astonished.jpeg"
S12 = "s12-build-here.jpeg"

# Caption text = verbatim spoken text, keyed by segment name.
TEXT = {s[0]: s[4] for s in make_narration.SEGMENTS}
KJV = {"jv24", "jv25", "jv26", "jv27"}

# BEATS: (segment_name, still, zoom_dir). One still-drift beat per narration
# segment; every word of that segment is captioned on it. Within a run on the SAME
# still the zoom alternates in/out/in, which is seamless: an "in" ends at 1.091 and
# the following "out" starts at 1.091, so consecutive beats on one image never jump.
BEATS = [
    ("n1", S1, "in"),
    ("n2", S2, "in"),
    ("n3", S3, "in"), ("n4", S3, "out"),
    ("jv24", S4, "in"),                         # THE WISE MAN / verse card — full silence
    ("n5", S5, "in"),
    ("jv25", S6, "in"),                         # "IT FELL NOT" — the payoff, full silence
    ("n6", S6, "out"),
    ("n7", S7, "in"), ("jv26", S7, "out"),     # the foolish man — UNDER the bed
    ("n8", S8, "in"),
    ("jv27", S9, "in"), ("n9", S9, "out"),     # the fall — restrained, UNDER the bed
    ("n10", S10, "in"),
    ("n11", S11, "in"),
    ("n12", S12, "in"),
]

LEAD = 0.28          # audio starts this long after its beat begins
GAP = 0.65           # trailing pad after SPOKEN content on a normal beat
KJV_GAP = 1.60       # a longer, reverent pad after a Jesus line
CARD_HOLD = 4.2      # extra seconds the card is held after it is read

# Every beat is timed from the SPOKEN end of its mp3, never the file end. The TTS
# files carry a silent tail — ~0.45s on the narrator, ~1.3s on the Jesus voice — and
# timing off the file end silently ADDS that tail to every pause, which is how video
# #39's first cut pushed two KJV pauses past the 2.5s No-Dead-Air law. Measured
# spoken length + explicit gap = the gap you actually hear.


def run(cmd):
    print(">>", " ".join(str(c) for c in cmd)[:130], flush=True)
    subprocess.run(cmd, check=True, capture_output=True)


def dur_of(path):
    out = subprocess.run(
        [FPROBE, "-v", "error", "-show_entries", "format=duration",
         "-of", "csv=p=0", path], capture_output=True, text=True)
    return float(out.stdout.strip())


def spoken_of(path):
    """Duration of `path` up to its LAST spoken sound (trailing silence removed)."""
    tmp = f"{S}/_spoken.wav"
    run([FF, "-y", "-v", "error", "-i", path, "-af",
         "areverse,silenceremove=start_periods=1:start_threshold=-50dB:"
         "start_duration=0.02,areverse", "-c:a", "pcm_s16le", tmp])
    return dur_of(tmp)


def wrapped(name):
    return "\n".join(textwrap.wrap(TEXT[name], width=34))


def _cap_chunks(text, width, max_lines):
    words = text.split()
    chunks, cur = [], ""
    for w in words:
        cand = (cur + " " + w).strip()
        if len(textwrap.wrap(cand, width)) <= max_lines:
            cur = cand
        else:
            chunks.append(cur)
            cur = w
    if cur:
        chunks.append(cur)
    return chunks


def caption_overlay(seg_id, dur, text, kjv):
    # CAPTION LAW (Cameron, 2026-07-17): a caption may occupy only the bottom
    # band of the frame — narrator <=2 lines, KJV <=3 lines per chunk; a longer
    # segment is SPLIT into chunks shown in sync with the narration (each chunk
    # holds for its share of the spoken time). Never shrink the font to cram.
    # One drawtext per LINE: this box's ffmpeg draws a textfile newline as a
    # tofu box, so a newline never enters a textfile.
    text = " ".join(text.split())
    if kjv:
        font, size, color, width, maxl = SERIF_BI, 46, "0xFFF3DC", 38, 3
    else:
        font, size, color, width, maxl = SERIF, 34, "white", 48, 2
    lh = int(size * 1.34)
    gap = KJV_GAP if kjv else GAP
    chunks = _cap_chunks(text, width, maxl)
    total = sum(len(c) for c in chunks) or 1
    t0 = 0.15
    t1 = max(t0 + 0.4, min(dur - 0.2, (dur - gap) + 0.35))
    chain = f"color=c=black@0.0:s=1080x1920:r={FPS}:d={dur},format=rgba"
    acc = 0
    for i, c in enumerate(chunks):
        cs = t0 + (t1 - t0) * acc / total
        acc += len(c)
        ce = t0 + (t1 - t0) * acc / total
        lines = textwrap.wrap(c, width)
        L = len(lines)
        for j, ln in enumerate(lines):
            tf = f"{S}/{seg_id}_c{i}_{j}.txt"
            with open(tf, "w", encoding="utf-8") as f:
                f.write(ln)
            y = f"h-120-text_h-{(L - 1 - j) * lh}"
            chain += (
                f",drawtext=fontfile='{font}':textfile='{tf}':fontsize={size}:"
                f"fontcolor={color}:x=(w-text_w)/2:y={y}:"
                f"shadowcolor=black@0.9:shadowx=2:shadowy=2:"
                f"box=1:boxcolor=black@0.58:boxborderw=22:"
                f"enable='between(t,{cs:.2f},{ce:.2f})'"
            )
    return chain + "[cap]"


def build_still(seg_id, src, dur, zdir, cap_text, kjv, first):
    # ANTI-SHIMMER: the drift is rendered supersampled (2160 wide) and lanczos'd
    # down to 1080, so zoompan's whole-pixel crop stepping lands on quarter-pixels
    # instead of showing as slideshow jitter.
    frames = int(dur * FPS)
    if zdir == "in":
        z = f"1.001+0.09*on/{frames}"
    else:
        z = f"1.091-0.09*on/{frames}"
    base = (f"[0:v]scale=2160:3868,setsar=1,"
            f"zoompan=z='{z}':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':"
            f"d={frames}:s=2160x3840:fps={FPS},"
            f"scale=1080:1920:flags=lanczos")
    capf = caption_overlay(seg_id, dur, cap_text, kjv)
    tail = ",fade=t=in:st=0:d=1.0" if first else ""
    fc = f"{base}[b];{capf};[b][cap]overlay=format=auto{tail}[v]"
    run([FF, "-y", "-loop", "1", "-i", f"{A}/{src}", "-t", str(dur),
         "-filter_complex", fc, "-map", "[v]"] + ENC + [f"{S}/{seg_id}.mp4"])


def build_card(dur, text):
    # per-line card (2026-07-17, #7 end-card tofu fix): this box renders a
    # textfile newline as a tofu box, so each wrapped card line gets its own
    # textfile + drawtext, block-centered. Visuals/audio unchanged.
    _clines = textwrap.wrap(text, width=30)
    _clh = 52 + 24
    _cL = len(_clines)
    _cdt = ""
    for _cj, _cln in enumerate(_clines):
        _ctf = f"{S}/card_{_cj}.txt"
        with open(_ctf, "w", encoding="utf-8") as _cf:
            _cf.write(_cln)
        _cy = f"(h-{_cL * _clh})/2+{_cj * _clh}"
        _cdt += (f"drawtext=fontfile={SERIF}:textfile={_ctf}:"
                 f"fontsize=52:fontcolor={INK}:x=(w-text_w)/2:y={_cy},")
    vf = _cdt + f"fade=t=in:st=0:d=0.8,fade=t=out:st={dur-0.8}:d=0.8"
    run([FF, "-y", "-f", "lavfi",
         "-i", f"color=c={CREAM}:s=1080x1920:r={FPS}:d={dur}",
         "-vf", vf] + ENC + [f"{S}/card.mp4"])


def bed_filter(idx, start, end, style):
    # No bare sine waves: every voice is a slightly detuned PAIR (natural slow
    # beating) through a soft room echo.
    d = end - start
    if d <= 1.0:
        return None
    if style == "a":
        # HUM PURGE (Cameron, 2026-07-16): the sine 'music bed' reads as a background hum in every video — amplitudes zeroed. Do not restore; narration + silence only (PRODUCTION-BIBLE #5b 2026-07-16).
        src = ("aevalsrc='0*(sin(2*PI*110*t)+sin(2*PI*110.6*t))"
               "+0*(sin(2*PI*164.81*t)+sin(2*PI*165.5*t))"
               "+0*sin(2*PI*220*t)+0*sin(2*PI*329.63*t)'")
        eq = "lowpass=f=760,tremolo=f=0.12:d=0.3,aecho=0.7:0.4:311|429:0.24|0.17"
        fin, fout = 6, 6
    else:
        # HUM PURGE (Cameron, 2026-07-16): the sine 'music bed' reads as a background hum in every video — amplitudes zeroed. Do not restore; narration + silence only (PRODUCTION-BIBLE #5b 2026-07-16).
        src = ("aevalsrc='0*(sin(2*PI*110*t)+sin(2*PI*110.5*t))"
               "+0*(sin(2*PI*146.83*t)+sin(2*PI*147.4*t))"
               "+0*sin(2*PI*196*t)+0*sin(2*PI*220*t)'")
        eq = "lowpass=f=700,tremolo=f=0.10:d=0.3,aecho=0.7:0.4:317|443:0.24|0.17"
        fin, fout = 6, 7
    ms = int(start * 1000)
    delay = f",adelay={ms}|{ms}" if ms else ""
    fin = min(fin, d / 3)
    fout = min(fout, d / 3)
    return (f"{src}:s=44100:d={d:.3f},{eq},"
            f"afade=t=in:st=0:d={fin:.2f},afade=t=out:st={d-fout:.2f}:d={fout:.2f}"
            f"{delay}[mus{idx}]")


def main():
    os.makedirs(S, exist_ok=True)

    # ---- compute the timeline from MEASURED audio (never estimates) ----
    # The mp3 still plays in full; its silent tail simply overlaps the next beat's
    # lead-in, which is harmless. Only the TIMING is driven by the spoken end.
    spoken = {n: spoken_of(f"audio/{n}.mp3") for n, _, _ in BEATS}
    card_spoken = spoken_of("audio/card.mp3")

    timeline = []     # (seg_id, still, zoom, video_dur, audio_start, kjv)
    audio_place = []  # (mp3, start)
    start_of = {}     # seg_id -> audio start, for scheduling the music beds
    t = 0.0
    for name, still, zdir in BEATS:
        kjv = name in KJV
        gap = KJV_GAP if kjv else GAP
        vdur = LEAD + spoken[name] + gap
        a_start = t + LEAD
        audio_place.append((f"audio/{name}.mp3", a_start))
        start_of[name] = a_start
        timeline.append((name, still, zdir, vdur, a_start, kjv))
        t += vdur
    card_vdur = LEAD + card_spoken + CARD_HOLD
    card_start = t
    audio_place.append(("audio/card.mp3", card_start + LEAD))
    total = t + card_vdur

    # ---- on-paper silence map: prove no spoken gap exceeds 2.5s BEFORE mixing ----
    # This RAISES rather than warns. A checker that can only print is a checker that
    # gets ignored; the No-Dead-Air law has to be unshippable to break.
    worst, worst_at = 0.0, None
    prev_end = None
    for name, _s, _z, _v, a_start, _k in timeline:
        if prev_end is not None and a_start - prev_end > worst:
            worst, worst_at = a_start - prev_end, name
        prev_end = a_start + spoken[name]
    print(f"total runtime: {total:.1f}s ({total/60:.2f} min)", flush=True)
    print(f"worst spoken gap: {worst:.2f}s before {worst_at} "
          f"(No-Dead-Air law: must be <= 2.5s)", flush=True)
    if worst > 2.5:
        raise SystemExit(f"DEAD AIR: {worst:.2f}s gap before {worst_at} "
                         f"exceeds the 2.5s law")
    print(f"sacred silence 1 (wise/rock): jv24 at {start_of['jv24']:.1f}s", flush=True)
    print(f"sacred silence 2 (it fell not): jv25 at {start_of['jv25']:.1f}s", flush=True)

    # ---- render every still beat ----
    for i, (seg_id, still, zdir, vdur, _a, kjv) in enumerate(timeline):
        build_still(seg_id, still, vdur, zdir, wrapped(seg_id), kjv,
                    first=(i == 0))
    build_card(card_vdur, TEXT["card"])

    with open(f"{S}/concat.txt", "w") as f:
        for seg_id, *_ in timeline:
            f.write(f"file '{seg_id}.mp4'\n")
        f.write("file 'card.mp4'\n")
    run([FF, "-y", "-f", "concat", "-safe", "0", "-i", f"{S}/concat.txt",
         "-c", "copy", f"{S}/video_silent.mp4"])

    # ---- audio: narration at computed offsets + warm beds around two silences ----
    p1_end = start_of["jv24"] + spoken["jv24"]
    p2_end = start_of["jv25"] + spoken["jv25"]
    beds = [
        # carries the story in; out before the wise-man verse card
        (0.0, start_of["jv24"] - 1.2, "b"),
        # returns to carry the calm-before-the-storm; dies before "it fell not"
        (p1_end + 1.0, start_of["jv25"] - 1.0, "a"),
        # returns to carry the foolish vignette, the morning-after, the frame and the
        # invitation; gone before the closing card. jv26/jv27 (the foolish man and the
        # fall) play UNDER this soft bed on purpose — the weight stays on the rock.
        (p2_end + 1.0, card_start - 0.8, "a"),
    ]
    print(f"music: bed out at {start_of['jv24'] - 1.2:.1f}s, silent through jv24 "
          f"(ends {p1_end:.1f}s); returns under n5; silent again through jv25 "
          f"(ends {p2_end:.1f}s)", flush=True)

    inputs, filters, labels = [], [], []
    for i, (path, start) in enumerate(audio_place):
        inputs += ["-i", path]
        ms = int(start * 1000)
        filters.append(
            f"[{i}:a]aresample=44100,adelay={ms}|{ms},volume=1.0[a{i}]")
        labels.append(f"[a{i}]")
    bi = 0
    for (bs, be, st) in beds:
        bf = bed_filter(bi, bs, be, st)
        if bf:
            filters.append(bf)
            labels.append(f"[mus{bi}]")
            bi += 1
    m = len(labels)
    filters.append("".join(labels) +
                   f"amix=inputs={m}:duration=longest:normalize=0,"
                   f"apad=whole_dur={total:.2f}[aout]")
    run([FF, "-y"] + inputs + ["-filter_complex", ";".join(filters),
        "-map", "[aout]", "-t", f"{total:.2f}", "-c:a", "aac", "-b:a", "160k",
        f"{S}/audio_mix.m4a"])

    # ---- loudness toward -15 LUFS (quiet audio reads as amateur) ----
    probe = subprocess.run(
        [FF, "-i", f"{S}/audio_mix.m4a", "-af", "ebur128", "-f", "null", "-"],
        capture_output=True, text=True)
    lufs = None
    for line in probe.stderr.splitlines():
        line = line.strip()
        if line.startswith("I:") and "LUFS" in line:
            lufs = float(line.split()[1])
    gain = max(-6.0, min(10.0, -15.0 - lufs)) if lufs is not None else 0.0
    print(f"loudness: measured {lufs} LUFS, applying {gain:+.1f} dB", flush=True)

    # ---- final mux: the ONLY lossy generation. Never starve the bitrate. ----
    # The old cap (24.3*8000/total - 130) did NOT subtract the real audio track, so
    # on a long video it asked for more bits than the 25MB law leaves and the encode
    # loop just climbed CRF until something fit. Compute the VIDEO budget honestly:
    # container budget minus the actual audio bitrate minus mux overhead. Then the
    # FIRST crf pass already lands in budget and the loop is only a safety net.
    OUT = "matthew-7_houses-on-rock-and-sand.mp4"
    A_KBPS = 96          # AAC at 96k is transparent for a dry narration track
    MUX = 20             # container/index overhead, kbps
    vcap = int(24.0 * 8000 / total) - A_KBPS - MUX
    # A painted still under a slow Ken Burns drift is very compressible, but below
    # roughly 400 kbps at 1080x1920 the gradients start to band. If the honest budget
    # cannot buy that, the video is simply TOO LONG for the <25MB law — say so loudly
    # rather than shipping a blocky video (PRODUCTION-BIBLE: never starve the bitrate).
    if vcap < 400:
        raise SystemExit(
            f"BITRATE STARVED: {total:.0f}s only leaves {vcap} kbps of video inside "
            f"the 25MB law (need >=400). Shorten the script — do not ship blocking.")
    print(f"video budget: {vcap} kbps ({total:.0f}s, {A_KBPS}k audio)", flush=True)

    size, crf = 0.0, 20
    for crf in (20, 21, 22, 23, 24):
        run([FF, "-y", "-i", f"{S}/video_silent.mp4",
             "-i", f"{S}/audio_mix.m4a", "-map", "0:v", "-map", "1:a",
             "-c:v", "libx264", "-preset", "slow", "-crf", str(crf),
             "-maxrate", f"{vcap}k", "-bufsize", f"{vcap*2}k",
             "-pix_fmt", "yuv420p",
             "-af", f"volume={gain:.1f}dB,alimiter=limit=0.95",
             "-c:a", "aac", "-b:a", f"{A_KBPS}k", "-movflags", "+faststart", OUT])
        size = os.path.getsize(OUT) / 1e6
        if size <= 24.3:
            break
        print(f"  {size:.1f} MB at crf {crf} — over, stepping up", flush=True)
    print(f"DONE: {OUT}  {size:.1f} MB, {total:.1f}s (crf {crf}, vcap {vcap}k)",
          flush=True)


if __name__ == "__main__":
    main()
