#!/usr/bin/env node
/**
 * gen_kjv.js — build the bundled, inline KJV text for the MILK track.
 *
 * LEGAL / SCRIPTURE-ARCHITECTURE NOTE (Cameron, June 2026):
 *   The 100 MILK items are Bible-only and are rendered IN-APP so a seeker never
 *   has to leave for foundational verses. We embed ONLY the public-domain King
 *   James Version text for those exact milk passages. The modern editions of the
 *   Book of Mormon, Doctrine and Covenants, and Pearl of Great Price (with their
 *   headings and footnotes) are copyrighted by The Church of Jesus Christ of
 *   Latter-day Saints and are NEVER embedded — meat items only ever link out to
 *   the official Gospel Library. This keeps the app legally clean.
 *
 * SOURCE: the public-domain `kjv` npm package (1769 Authorized Version). We do NOT
 * ship the whole 5.7 MB Bible into the app — only the ~100 cited milk passages.
 *
 * USAGE (re-run whenever the milk corpus changes):
 *   1) cd /tmp && npm install kjv   (or anywhere; pass --kjv <path to verses json>)
 *   2) node tools/gen_kjv.js [--kjv /tmp/kjvgen/node_modules/kjv/json/verses-1769.json]
 *   It reads tools/content.data.json (the generated corpus) and writes
 *   mobile/src/data/kjvText.ts.
 */
const fs   = require('fs');
const path = require('path');

const ROOT     = path.resolve(__dirname, '..');
const DATA     = path.join(ROOT, 'tools', 'content.data.json');
const OUT      = path.join(ROOT, 'mobile', 'src', 'data', 'kjvText.ts');
const kjvArg   = process.argv.indexOf('--kjv');
const KJV_JSON = kjvArg !== -1 ? process.argv[kjvArg + 1]
                               : '/tmp/kjvgen/node_modules/kjv/json/verses-1769.json';

const kjv = require(KJV_JSON); // { "Book C:V": "text", ... }

// Some milk refs say "Psalm 23"; the KJV keys use "Psalms".
const BOOK_ALIAS = { Psalm: 'Psalms' };

function clean(text) {
  // The 1769 text marks supplied (italic) words with [brackets] and starts a new
  // paragraph with "#" (the ¶ pilcrow). Drop the brackets (keep the words) and the
  // paragraph markers for clean inline reading.
  return text
    .replace(/#/g, '')
    .replace(/[\[\]]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
}

// Parse "Book C", "Book C:V", "Book C:V-W" -> ordered list of {ref, text}.
function versesFor(ref) {
  const m = ref.match(/^(\d?\s?[A-Za-z ]+?)\s+(\d+)(?::(\d+)(?:-(\d+))?)?$/);
  if (!m) return null;
  let [, book, chap, v1, v2] = m;
  book = book.trim();
  book = BOOK_ALIAS[book] || book;
  const chapter = Number(chap);
  const out = [];

  if (!v1) {
    // Whole chapter — walk verses until the key runs out.
    for (let v = 1; ; v++) {
      const key = `${book} ${chapter}:${v}`;
      if (!(key in kjv)) break;
      out.push({ ref: key, text: clean(kjv[key]) });
    }
  } else {
    const start = Number(v1);
    const end   = v2 ? Number(v2) : start;
    for (let v = start; v <= end; v++) {
      const key = `${book} ${chapter}:${v}`;
      if (key in kjv) out.push({ ref: key, text: clean(kjv[key]) });
    }
  }
  return out.length ? out : null;
}

const raw  = JSON.parse(fs.readFileSync(DATA, 'utf8'));
const arr  = Array.isArray(raw) ? raw : (raw.CONTENT || raw.content || []);
const milk = arr.filter(c => c.track === 'MILK');

const map     = {};
const missing = [];
let maxVerses = 0;
for (const item of milk) {
  const verses = versesFor(item.scriptureRef);
  if (!verses) { missing.push(`${item.id}: ${item.scriptureRef}`); continue; }
  map[item.id] = verses;
  maxVerses = Math.max(maxVerses, verses.length);
}

if (missing.length) {
  console.error('MISSING KJV TEXT for:\n  ' + missing.join('\n  '));
  process.exit(1);
}

const header = `// AUTO-GENERATED by tools/gen_kjv.js — do not edit by hand.
//
// Inline, public-domain King James Version text for the 100 MILK (Bible-only)
// content items, keyed by content id. Rendered in-app by ContentCard so a seeker
// never has to leave for a foundational verse.
//
// COPYRIGHT NOTE: Modern editions of the Book of Mormon, Doctrine and Covenants,
// and Pearl of Great Price (including their headings and footnotes) are
// copyrighted by The Church of Jesus Christ of Latter-day Saints. Only
// public-domain KJV text is embedded here, and only for the milk track. MEAT
// (restored-scripture) items NEVER embed text — they link to the official
// Gospel Library instead. See ContentCard.tsx.

export interface KjvVerse { ref: string; text: string }

export const KJV_TEXT: Record<number, KjvVerse[]> = ${JSON.stringify(map, null, 2)};

export function kjvVersesFor(id: number): KjvVerse[] | undefined {
  return KJV_TEXT[id];
}
`;

fs.writeFileSync(OUT, header);
console.log(`Wrote ${OUT}`);
console.log(`milk items: ${milk.length}, with text: ${Object.keys(map).length}, longest passage: ${maxVerses} verses`);
