#!/usr/bin/env python3
"""
audit_review_state.py — one honest picture of what the reviewer is actually seeing.

Cameron's complaint: "the reviewer is still showing me old videos that haven't been
reworked." The review page (site/review.html) is a STATIC snapshot generated by
gen_site_index.py. Each video streams straight from
github.com/.../main/media-production/build-NN/<mp4> and the page buckets a video as
"new voice / reworked" ONLY when its mp4 was committed at/after the SPEAKER-LAW cutoff.

So a video shows up as OLD in the reviewer whenever ANY of these is true:
  1. its mp4 was never rebuilt+committed since the cutoff (not reworked at all), OR
  2. it WAS reworked on disk but never committed/pushed (session left it local), OR
  3. it was reworked+pushed AFTER review.html was last generated (page is stale), OR
  4. the URL in review.html points at a folder/file that no longer exists (slug drift).

This script computes the TRUTH from git right now and diffs it against the deployed
review.html, then writes AUDIT-REVIEW-STATE.md with a per-video table + summary.
It is read-only: it runs git plумbing and hashes files, changes nothing.
"""
import os, re, subprocess, html, glob, datetime

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MP = os.path.join(REPO, "media-production")
REVIEW_HTML = os.path.join(REPO, "site", "review.html")
NEW_VOICE_SINCE = 1784395766  # 2026-07-18 13:29 — SPEAKER LAW cutoff (from gen_site_index.py)

MP4_RE = re.compile(r"media-production/build-(\d+)-.*/[0-9a-z]+-\d+_.*\.mp4$")


def git(*args):
    return subprocess.run(["git", *args], cwd=REPO, capture_output=True, text=True).stdout


def committed_mp4s():
    """num -> (path, blob_hash) for the one scripture-named mp4 committed at HEAD."""
    out = git("ls-tree", "-r", "HEAD", "--", "media-production")
    res = {}
    for line in out.splitlines():
        try:
            meta, path = line.split("\t", 1)
            _, _typ, h = meta.split()
        except ValueError:
            continue
        m = MP4_RE.match(path)
        if m:
            res[int(m.group(1))] = (path, h)
    return res


def new_voice_committed():
    """Set of nums whose mp4 was committed at/after the cutoff — the true 'reworked'."""
    out = git("log", f"--since=@{NEW_VOICE_SINCE}", "--name-only", "--format=",
              "--", "media-production")
    found = set()
    for line in out.splitlines():
        m = MP4_RE.match(line.strip())
        if m:
            found.add(int(m.group(1)))
    return found


def last_mp4_commit(path):
    out = git("log", "-1", "--format=%ci|%h", "--", path).strip()
    return out if out else ""


def worktree_blob(path_abs):
    """git blob hash of the file as it sits on disk (uncommitted content)."""
    if not os.path.exists(path_abs):
        return None
    return git("hash-object", path_abs).strip() or None


def local_disk_mp4(num, build_dirs):
    """The scripture-named mp4 physically on disk for this build, if any."""
    bd = build_dirs.get(num)
    if not bd:
        return None
    hits = [p for p in glob.glob(os.path.join(bd, "*.mp4"))
            if re.match(r"[0-9a-z]+-\d+_.*\.mp4$", os.path.basename(p))
            and ".orig." not in os.path.basename(p)]
    return sorted(hits)[0] if hits else None


def parse_review_html():
    """num -> {'hash':..., 'newvoice':bool, 'src':url} from the deployed page."""
    if not os.path.exists(REVIEW_HTML):
        return {}, None
    txt = open(REVIEW_HTML, encoding="utf-8").read()
    cards = {}
    # card divs carry data-num/data-hash/optional data-newvoice; a <video src> follows
    for m in re.finditer(
            r'data-num="(\d+)"\s+data-hash="([0-9a-f]*)"(\s+data-newvoice="1")?', txt):
        cards[int(m.group(1))] = {"hash": m.group(2),
                                  "newvoice": bool(m.group(3)), "src": None}
    for m in re.finditer(r'data-num="(\d+)".*?<video[^>]*src="([^"]+)"', txt, re.S):
        n = int(m.group(1))
        if n in cards:
            cards[n]["src"] = m.group(2)
    gen = None
    gm = re.search(r"generated[^0-9]*(\d{4}-\d\d-\d\d[ T][\d:]+)", txt, re.I)
    if gm:
        gen = gm.group(1)
    return cards, gen


def main():
    build_dirs = {}
    for bd in glob.glob(os.path.join(MP, "build-*")):
        m = re.match(r"build-(\d+)-", os.path.basename(bd))
        if m and os.path.isdir(bd):
            build_dirs.setdefault(int(m.group(1)), bd)  # first slug wins if dupes

    committed = committed_mp4s()
    reworked = new_voice_committed()
    review, gen = parse_review_html()
    review_committed_hashes = {c["hash"] for c in review.values() if c.get("hash")}

    nums = sorted(set(committed) | set(review) | set(build_dirs))
    rows = []
    for n in nums:
        path, chash = committed.get(n, (None, None))
        disk = local_disk_mp4(n, build_dirs)
        disk_hash = worktree_blob(disk) if disk else None
        uncommitted = bool(disk_hash and chash and disk_hash != chash)
        missing_on_disk = disk is None
        rv = review.get(n, {})
        rv_hash = rv.get("hash")
        rv_new = rv.get("newvoice", False)
        # link target on the page still resolvable to a real committed file?
        src = rv.get("src") or ""
        srcm = re.search(r"media-production/(build-\d+-[^/]+/[^\"]+\.mp4)$", src)
        src_rel = srcm.group(1) if srcm else None
        src_exists = bool(src_rel and os.path.exists(os.path.join(MP, src_rel)))

        # classify
        if n not in review:
            status = "NOT-ON-PAGE"          # built but review.html never included it
        elif not src_exists and src_rel:
            status = "BROKEN-LINK"          # page points at a missing file (slug drift)
        elif uncommitted:
            status = "LOCAL-NOT-PUSHED"     # reworked on disk, never committed → reviewer old
        elif n in reworked and rv_hash == chash and rv_new:
            status = "REWORKED-LIVE"        # new cut, committed, page shows it as new
        elif n in reworked and rv_hash != chash:
            status = "STALE-PAGE"           # reworked+committed but page snapshot is behind
        elif n in reworked and not rv_new:
            status = "STALE-PAGE"           # committed since cutoff but page still tags old
        elif n not in reworked:
            status = "OLD-NOT-REWORKED"     # no rebuild since cutoff → genuinely old
        else:
            status = "REWORKED-LIVE"
        rows.append(dict(num=n, path=path, chash=chash, disk_hash=disk_hash,
                         uncommitted=uncommitted, missing_on_disk=missing_on_disk,
                         reworked=n in reworked, rv_hash=rv_hash, rv_new=rv_new,
                         src_rel=src_rel, src_exists=src_exists, status=status,
                         last=last_mp4_commit(path) if path else ""))

    # summary
    from collections import Counter
    counts = Counter(r["status"] for r in rows)
    total = len(rows)

    def cut(ts):
        return datetime.datetime.utcfromtimestamp(NEW_VOICE_SINCE).strftime("%Y-%m-%d %H:%M UTC")

    lines = []
    lines.append("# AUDIT — What the reviewer is actually seeing (old vs reworked)\n")
    lines.append(f"_Generated by `audit_review_state.py` (read-only). "
                 f"Reworked cutoff (SPEAKER LAW) = {cut(NEW_VOICE_SINCE)}._\n")
    lines.append(f"- Deployed `site/review.html` last git commit: "
                 f"`{last_mp4_commit(os.path.join('site','review.html')) or 'n/a'}`")
    lines.append(f"- Videos on the review page: **{len(review)}** · "
                 f"build folders on disk: **{len(build_dirs)}** · "
                 f"mp4s committed at HEAD: **{len(committed)}**\n")
    lines.append("## Summary\n")
    label = {
        "OLD-NOT-REWORKED": "🔴 OLD — never rebuilt since the new-voice cutoff (genuinely not reworked yet)",
        "LOCAL-NOT-PUSHED": "🟠 REWORKED LOCALLY BUT NOT PUSHED — a session built it; reviewer still streams the old committed cut",
        "STALE-PAGE": "🟡 REWORKED & PUSHED, BUT review.html is STALE — regenerate + redeploy the page",
        "BROKEN-LINK": "⛔ BROKEN LINK — page points at a file that no longer exists (slug drift)",
        "NOT-ON-PAGE": "⚪ BUILT BUT NOT ON THE PAGE — mp4 exists but no review card",
        "REWORKED-LIVE": "🟢 REWORKED & LIVE — new cut, committed, page shows it correctly",
    }
    for k in ["REWORKED-LIVE", "STALE-PAGE", "LOCAL-NOT-PUSHED", "OLD-NOT-REWORKED",
              "BROKEN-LINK", "NOT-ON-PAGE"]:
        if counts.get(k):
            lines.append(f"- **{counts[k]}** · {label[k]}")
    lines.append(f"\n**Total audited: {total}**\n")

    # actionable buckets first
    def numlist(st):
        return ", ".join(str(r["num"]) for r in rows if r["status"] == st) or "—"
    lines.append("## Action lists (video numbers)\n")
    lines.append(f"- Regenerate+redeploy review page fixes these **STALE-PAGE**: {numlist('STALE-PAGE')}")
    lines.append(f"- Commit+push needed (**LOCAL-NOT-PUSHED**): {numlist('LOCAL-NOT-PUSHED')}")
    lines.append(f"- Still need a real rework (**OLD-NOT-REWORKED**): {numlist('OLD-NOT-REWORKED')}")
    lines.append(f"- Broken links to fix (**BROKEN-LINK**): {numlist('BROKEN-LINK')}")
    lines.append(f"- Built but missing a review card (**NOT-ON-PAGE**): {numlist('NOT-ON-PAGE')}\n")

    lines.append("## Per-video detail\n")
    lines.append("| # | status | reworked(git) | page=new | page hash==HEAD | local uncommitted | last mp4 commit | build path |")
    lines.append("|---|---|---|---|---|---|---|---|")
    for r in rows:
        hash_match = "—"
        if r["rv_hash"] is not None and r["chash"]:
            hash_match = "yes" if r["rv_hash"] == r["chash"] else "**NO**"
        pathdisp = (r["path"] or (build_dirs.get(r["num"], "?").replace(REPO + "/", "") + "/ (no mp4)"))
        lines.append(
            f"| {r['num']} | {r['status']} | {'yes' if r['reworked'] else 'no'} | "
            f"{'yes' if r['rv_new'] else ('no' if r['num'] in review else '—')} | "
            f"{hash_match} | {'YES' if r['uncommitted'] else ('missing' if r['missing_on_disk'] else 'no')} | "
            f"{r['last'].split('|')[0][:16] if r['last'] else '—'} | {pathdisp} |")

    out = os.path.join(MP, "AUDIT-REVIEW-STATE.md")
    open(out, "w", encoding="utf-8").write("\n".join(lines) + "\n")

    # console summary
    print(f"Wrote {out}")
    print(f"\nReviewer audit — {total} videos:")
    for k in ["REWORKED-LIVE", "STALE-PAGE", "LOCAL-NOT-PUSHED", "OLD-NOT-REWORKED",
              "BROKEN-LINK", "NOT-ON-PAGE"]:
        if counts.get(k):
            print(f"  {counts[k]:>3}  {k}")


if __name__ == "__main__":
    main()
